Chess: /Users/runner/work/chess/chess/src/game/PawnColor.cpp File Reference
PawnColor.cpp File Reference
#include <game/PawnColor.h>
Functions
std::string pawnColorToString (const PawnColor &color)
template<typename T >
std::string operator+ (const T &lhs, const PawnColor &color)
template<typename T >
std::string operator+ (const PawnColor &color, const T &rhs)
std::string operator+ (const PawnColor &color1, const PawnColor &color2)
std::ostream & operator<< (std::ostream &lhs, const PawnColor &color)
template std::string operator+ (const std::string &lhs, const PawnColor &color)
template std::string operator+ (const PawnColor &color, const std::string &rhs)
Function Documentation
operator+() [1/5]
template std::string operator+ (const PawnColor & color, const std::string & rhs)
operator+() [2/5]
template<typename T > std::string operator+ (const PawnColor & color, const T & rhs)
{
  return pawnColorToString(color) + rhs;
}
References pawnColorToString().
operator+() [3/5]
std::string operator+ (const PawnColor & color1, const PawnColor & color2)
{
  return pawnColorToString(color1) + pawnColorToString(color2);
}
References pawnColorToString().
operator+() [4/5]
template std::string operator+ (const std::string & lhs, const PawnColor & color)
operator+() [5/5]
template<typename T > std::string operator+ (const T & lhs, const PawnColor & color)
{
  return lhs + pawnColorToString(color);
}
References pawnColorToString().
operator<<()
std::ostream & operator<< (std::ostream & lhs, const PawnColor & color)
{
  return lhs << pawnColorToString(color);
}
References pawnColorToString().
pawnColorToString()
std::string pawnColorToString (const PawnColor & color)
{
  if (color == PawnColor::WHITE) {
    return "white";
  } else {
    return "black";
  }
}
References WHITE.
Referenced by operator+(), and operator<<().