Chess: MenuOption Class Reference
MenuOption Class Reference
#include <MenuOption.h>
Public Member Functions
MenuOption (const HUD &hud)
std::weak_ptr< HUD > getMessage () const
std::weak_ptr< Rectangle > getButton () const
void playSound () const
Private Attributes
std::shared_ptr< HUD > optionHUD
std::shared_ptr< Rectangle > button {std::make_shared<Rectangle>()}
ClickSound clickSound {ClickSound()}
Constructor & Destructor Documentation
MenuOption()
MenuOption::MenuOption (const HUD & hud) explicit
                                     : optionHUD(std::make_shared<HUD>(hud)) {
  const auto [buttonX, buttonY]{this->optionHUD->getCoordinates()};
  const std::size_t size{this->optionHUD->getSize()};
  const float length{(this->optionHUD->getLength() * static_cast<float>(size) / 2) + 200.0f};
  this->button->setHeight(static_cast<float>(size) * 1.5f);
  this->button->setWidth(length);
  this->button->setLeftBottom(Point(buttonX - 50.0f, buttonY + (static_cast<float>(size) / 2)));
  this->button->setBrush(Brush::DARK_BROWN, Rectangle::colors.at(Brush::DARK_BROWN));
}
References button, Rectangle::colors, DARK_BROWN, and optionHUD.
Member Function Documentation
getButton()
std::weak_ptr< Rectangle > MenuOption::getButton () const
{
  return this->button;
}
References button.
getMessage()
std::weak_ptr< HUD > MenuOption::getMessage () const
{
  return this->optionHUD;
}
References optionHUD.
playSound()
void MenuOption::playSound () const
{
  this->clickSound.play();
}
References clickSound, and Sound::play().
Member Data Documentation
button
std::shared_ptr<Rectangle> MenuOption::button {std::make_shared<Rectangle>()} private
Referenced by getButton(), and MenuOption().
clickSound
ClickSound MenuOption::clickSound {ClickSound()} private
Referenced by playSound().
optionHUD
std::shared_ptr<HUD> MenuOption::optionHUD private
Referenced by getMessage(), and MenuOption().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/src/graphics/graphics/MenuOption.h
/Users/runner/work/chess/chess/src/graphics/src/MenuOption.cpp