Chess: /Users/runner/work/chess/chess/src/game/game/PawnColor.h File Reference
PawnColor.h File Reference
#include <string>
#include <array>
Enumerations
enum class PawnColor { WHITE = 0 , BLACK = 1 }
Functions
template<typename T >
std::string operator+ (const T &lhs, const PawnColor &color)
template<typename T >
std::string operator+ (const PawnColor &color, const T &rhs)
std::string operator+ (const PawnColor &color1, const PawnColor &color2)
std::ostream & operator<< (std::ostream &lhs, const PawnColor &color)
std::string pawnColorToString (const PawnColor &color)
PawnColor operator! (const PawnColor &color)
Enumeration Type Documentation
PawnColor
enum class PawnColor strong
Enumerator
WHITE
BLACK
                     {
  WHITE = 0,
  BLACK = 1
};
Function Documentation
operator!()
PawnColor operator! (const PawnColor & color)
{
  PawnColor oppositeColor;
  if (color == PawnColor::WHITE) {
    oppositeColor = PawnColor::BLACK;
  } else {
    oppositeColor = PawnColor::WHITE;
  }
  return oppositeColor;
}
References BLACK, and WHITE.
operator+() [1/3]
template<typename T > std::string operator+ (const PawnColor & color, const T & rhs)
{
  return pawnColorToString(color) + rhs;
}
References pawnColorToString().
operator+() [2/3]
std::string operator+ (const PawnColor & color1, const PawnColor & color2)
{
  return pawnColorToString(color1) + pawnColorToString(color2);
}
References pawnColorToString().
operator+() [3/3]
template<typename T > std::string operator+ (const T & lhs, const PawnColor & color)
{
  return lhs + pawnColorToString(color);
}
References pawnColorToString().
operator<<()
std::ostream & operator<< (std::ostream & lhs, const PawnColor & color)
{
  return lhs << pawnColorToString(color);
}
References pawnColorToString().
pawnColorToString()
std::string pawnColorToString (const PawnColor & color)
{
  if (color == PawnColor::WHITE) {
    return "white";
  } else {
    return "black";
  }
}
References WHITE.
Referenced by PlayingScreen::displayCheck(), PlayingScreen::displayCheckmate(), operator+(), and operator<<().