Chess: Queen Class Reference
Queen Class Reference
#include <Queen.h>
Public Member Functions
Queen (PawnColor color)
std::vector< std::pair< int, int > > getAdvanceableSquares () override
std::vector< std::pair< int, int > > getHoldingSquares () override
std::weak_ptr< Pawn > getBlockedPawn () override
Public Member Functions inherited from Pawn
Pawn (PawnColor color)
void setSquare (const std::shared_ptr< Square > &square)
void capture (const std::shared_ptr< Pawn > &pawn)
std::weak_ptr< Square > getSquare () const
PawnColor getColor () const
void setTexture (std::string texture)
const std::string & getTexture () const
std::weak_ptr< Rectangle > getDrawingArea () const
void draw () override
void update (float ms) override
void move (float ms) override
void moveTo (const std::shared_ptr< Square > &squarePtr, const std::shared_ptr< Pawn > &self)
virtual std::vector< std::pair< int, int > > getAdvanceableSquares ()=0
virtual std::vector< std::pair< int, int > > getHoldingSquares ()=0
virtual std::vector< std::pair< int, int > > getAdvanceableSquares (const std::vector< pair > &steps, unsigned short int maxSteps, bool holding) const
std::vector< std::pair< int, int > > correctDirection (std::vector< std::pair< int, int > > steps) const
virtual std::weak_ptr< Pawn > getBlockedPawn ()
std::weak_ptr< Pawn > getBlockingPawn ()
bool isBlocked () const
void block ()
void unblock ()
void blockedBy (const std::shared_ptr< Pawn > &blocking)
void playCaptureSound ()
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Public Member Functions inherited from Movable
Movable ()=default
virtual void move (float ms)=0
virtual ~Movable ()=default
Private Attributes
std::vector< std::pair< int, int > > steps { std::vector<std::pair<int, int>>() }
Static Private Attributes
static constexpr unsigned short int maxSteps { 8 }
Constructor & Destructor Documentation
Queen()
Queen::Queen (PawnColor color) explicit
                            : Pawn(color) {
  Pawn::setTexture("queen");
  this->steps.push_back(std::make_pair<int, int>(1, 1));
  this->steps.push_back(std::make_pair<int, int>(-1, 1));
  this->steps.push_back(std::make_pair<int, int>(1, -1));
  this->steps.push_back(std::make_pair<int, int>(-1, -1));
  this->steps.push_back(std::make_pair<int, int>(1, 0));
  this->steps.push_back(std::make_pair<int, int>(-1, 0));
  this->steps.push_back(std::make_pair<int, int>(0, 1));
  this->steps.push_back(std::make_pair<int, int>(0, -1));
}
References Pawn::setTexture(), and steps.
Member Function Documentation
getAdvanceableSquares()
std::vector< std::pair< int, int > > Queen::getAdvanceableSquares () override virtual
Implements Pawn.
{
  return Pawn::getAdvanceableSquares(this->steps, Queen::maxSteps, false);
}
References Pawn::getAdvanceableSquares(), maxSteps, and steps.
getBlockedPawn()
std::weak_ptr< Pawn > Queen::getBlockedPawn () override virtual
Reimplemented from Pawn.
{
  auto game{static_cast<App *>(graphics::getUserData())->getGame().lock()};
  auto checkboard{game->getCheckboard()};
  const unsigned short int currentRow{this->getSquare().lock()->getRow()};
  const unsigned short int currentColumn{this->getSquare().lock()->getColumn()};
  unsigned short int nextRow{currentRow};
  unsigned short int nextColumn{currentColumn};
  for (const auto &[rowStep, columnStep]: Pawn::correctDirection(this->steps)) {
    bool shouldTerminate{false};
    std::shared_ptr<Pawn> pawn{nullptr};
    std::shared_ptr<Soldier> friendlySoldier{nullptr};
    std::shared_ptr<Soldier> enemySoldier{nullptr};
    unsigned short int numberOfSteps{0};
    while (!shouldTerminate) {
      nextRow += rowStep;
      nextColumn += columnStep;
      if ((nextRow >= Checkboard::sideSize || nextColumn >= Checkboard::sideSize) || numberOfSteps == Queen::maxSteps) {
        shouldTerminate = {true};
        continue;
      }
      ++numberOfSteps;
      const std::pair<int, int> squareCoordinates{std::make_pair<int, int>(nextRow, nextColumn)};
      const auto [hasPawn, pawnColor]{checkboard->getSquareInfo(squareCoordinates)};
      const bool blockEnPassant{(friendlySoldier != nullptr) && (enemySoldier != nullptr) && hasPawn && (checkboard->isKing(!Pawn::getColor(), squareCoordinates))};
      if (blockEnPassant) {
        const auto bannedSquare{std::make_pair(friendlySoldier->getSquare().lock()->getRow(), friendlySoldier->getSquare().lock()->getColumn())};
        enemySoldier->banEnPassantOn(bannedSquare);
        return std::weak_ptr<Pawn>();
      }
      const bool lonelyPawn{(((pawn == enemySoldier) && (enemySoldier != nullptr)) || ((pawn != nullptr) && (enemySoldier == nullptr)))};
      const bool blockPawn{(lonelyPawn) && (friendlySoldier == nullptr) && hasPawn && (checkboard->isKing(!Pawn::getColor(), squareCoordinates))};
      if (blockPawn) {
        return pawn;
      }
      if (hasPawn) {
        if (pawnColor != Pawn::getColor()) {
          if (pawn == nullptr) {
            pawn = {checkboard->getSquare(squareCoordinates).lock()->getPawn()};
          }
          if (enemySoldier == nullptr) {
            enemySoldier = {std::dynamic_pointer_cast<Soldier>(checkboard->getSquare(squareCoordinates).lock()->getPawn())};
          }
        } else {
          if (friendlySoldier == nullptr) {
            friendlySoldier = {std::dynamic_pointer_cast<Soldier>(checkboard->getSquare(squareCoordinates).lock()->getPawn())};
          }
        }
      }
    }
    nextRow = { currentRow };
    nextColumn = { currentColumn };
  }
  return std::weak_ptr<Pawn>();
}
References Pawn::correctDirection(), Pawn::getColor(), Pawn::getSquare(), maxSteps, Checkboard::sideSize, and steps.
getHoldingSquares()
std::vector< std::pair< int, int > > Queen::getHoldingSquares () override virtual
Implements Pawn.
{
  return Pawn::getAdvanceableSquares(this->steps, Queen::maxSteps, true);
}
References Pawn::getAdvanceableSquares(), maxSteps, and steps.
Member Data Documentation
maxSteps
constexpr unsigned short int Queen::maxSteps { 8 } static constexpr private
Referenced by getAdvanceableSquares(), getBlockedPawn(), and getHoldingSquares().
steps
std::vector<std::pair<int, int> > Queen::steps { std::vector<std::pair<int, int>>() } private
Referenced by getAdvanceableSquares(), getBlockedPawn(), getHoldingSquares(), and Queen().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/src/game/game/Queen.h
/Users/runner/work/chess/chess/src/game/src/Queen.cpp