Chess: /Users/runner/work/chess/chess/include/sgg/sgg/audio.cpp File Reference
audio.cpp File Reference
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <memory.h>
#include <SDL2/SDL.h>
#include "audio.h"
Classes
struct privateAudioDevice
Macros
#define AUDIO_FORMAT AUDIO_S16LSB
#define AUDIO_FREQUENCY 48000
#define AUDIO_CHANNELS 2
#define AUDIO_SAMPLES 4096
#define AUDIO_MAX_SOUNDS 25
#define SDL_AUDIO_ALLOW_CHANGES SDL_AUDIO_ALLOW_ANY_CHANGE
Typedefs
typedef struct privateAudioDevice PrivateAudioDevice
Functions
static void addMusic (Audio *root, Audio *news)
static void playAudio (const char *filename, Audio *audio, uint8_t loop, int volume)
static void addAudio (Audio *root, Audio *news)
static void audioCallback (void *userdata, uint8_t *stream, int len)
void playSound (const char *filename, int volume)
void playMusic (const char *filename, int volume)
void playSoundFromMemory (Audio *audio, int volume)
void playMusicFromMemory (Audio *audio, int volume)
void initAudio (void)
void endAudio (void)
void pauseAudio (void)
void unpauseAudio (void)
void freeAudio (Audio *audio)
Audio * createAudio (const char *filename, uint8_t loop, int volume)
Variables
static PrivateAudioDevice * gDevice
static uint32_t gSoundCount
Macro Definition Documentation
AUDIO_CHANNELS
#define AUDIO_CHANNELS 2
AUDIO_FORMAT
#define AUDIO_FORMAT AUDIO_S16LSB
AUDIO_FREQUENCY
#define AUDIO_FREQUENCY 48000
AUDIO_MAX_SOUNDS
#define AUDIO_MAX_SOUNDS 25
AUDIO_SAMPLES
#define AUDIO_SAMPLES 4096
SDL_AUDIO_ALLOW_CHANGES
#define SDL_AUDIO_ALLOW_CHANGES SDL_AUDIO_ALLOW_ANY_CHANGE
Typedef Documentation
PrivateAudioDevice
typedef struct privateAudioDevice PrivateAudioDevice
Function Documentation
addAudio()
static void addAudio (Audio * root, Audio * news) static
{
    if(root == NULL)
    {
        return;
    }
    while(root->next != NULL)
    {
        root = root->next;
    }
    root->next = news;
}
References sound::next.
Referenced by addMusic(), and playAudio().
addMusic()
static void addMusic (Audio * root, Audio * news) static
{
    uint8_t musicFound = 0;
    Audio * rootNext = root->next;
    /* Find any existing musics, 0, 1 or 2 and fade them out */
    while(rootNext != NULL)
    {
        /* Phase out any current music */
        if(rootNext->loop == 1 && rootNext->fade == 0)
        {
            if(musicFound)
            {
                rootNext->length = 0;
                rootNext->volume = 0;
            }
            rootNext->fade = 1;
        }
        /* Set flag to remove any queued up music in favour of new music */
        else if(rootNext->loop == 1 && rootNext->fade == 1)
        {
            musicFound = 1;
        }
        rootNext = rootNext->next;
    }
    addAudio(root, news);
}
References addAudio(), sound::fade, sound::length, sound::loop, sound::next, and sound::volume.
Referenced by playAudio().
audioCallback()
static void audioCallback (void * userdata, uint8_t * stream, int len) inline static
{
    Audio * audio = (Audio *) userdata;
    Audio * previous = audio;
    int tempLength;
    uint8_t music = 0;
    /* Silence the main buffer */
    SDL_memset(stream, 0, len);
    /* First one is place holder */
    audio = audio->next;
    while(audio != NULL)
    {
        if(audio->length > 0)
        {
            if(audio->fade == 1 && audio->loop == 1)
            {
                music = 1;
                if(audio->volume > 0)
                {
                    audio->volume--;
                }
                else
                {
                    audio->length = 0;
                }
            }
            if(music && audio->loop == 1 && audio->fade == 0)
            {
                tempLength = 0;
            }
            else
            {
                tempLength = ((uint32_t) len > audio->length) ? audio->length : (uint32_t) len;
            }
            SDL_MixAudioFormat(stream, audio->buffer, AUDIO_FORMAT, tempLength, audio->volume);
            audio->buffer += tempLength;
            audio->length -= tempLength;
            previous = audio;
            audio = audio->next;
        }
        else if(audio->loop == 1 && audio->fade == 0)
        {
            audio->buffer = audio->bufferTrue;
            audio->length = audio->lengthTrue;
        }
        else
        {
            previous->next = audio->next;
            if(audio->loop == 0)
            {
                gSoundCount--;
            }
            audio->next = NULL;
            freeAudio(audio);
            audio = previous->next;
        }
    }
}
References AUDIO_FORMAT, sound::buffer, sound::bufferTrue, sound::fade, freeAudio(), gSoundCount, sound::length, sound::lengthTrue, sound::loop, sound::next, and sound::volume.
Referenced by initAudio().
createAudio()
Audio * createAudio (const char * filename, uint8_t loop, int volume)
{
    Audio * news = (Audio*)calloc(1, sizeof(Audio));
    if(news == NULL)
    {
        fprintf(stderr, "[%s: %d]Error: Memory allocation error\n", __FILE__, __LINE__);
        return NULL;
    }
    if(filename == NULL)
    {
        fprintf(stderr, "[%s: %d]Warning: filename NULL: %s\n", __FILE__, __LINE__, filename);
        return NULL;
    }
    news->next = NULL;
    news->loop = loop;
    news->fade = 0;
    news->free = 1;
    news->volume = volume;
    if(SDL_LoadWAV(filename, &(news->audio), &(news->bufferTrue), &(news->lengthTrue)) == NULL)
    {
        fprintf(stderr, "[%s: %d]Warning: failed to open wave file: %s error: %s\n", __FILE__, __LINE__, filename, SDL_GetError());
        free(news);
        return NULL;
    }
    news->buffer = news->bufferTrue;
    news->length = news->lengthTrue;
    (news->audio).callback = NULL;
    (news->audio).userdata = NULL;
    return news;
}
References sound::audio, sound::buffer, sound::bufferTrue, sound::fade, sound::free, sound::length, sound::lengthTrue, sound::loop, sound::next, and sound::volume.
Referenced by playAudio().
endAudio()
void endAudio (void)
{
    if(gDevice->audioEnabled)
    {
        pauseAudio();
        freeAudio((Audio *) (gDevice->want).userdata);
        /* Close down audio */
        SDL_CloseAudioDevice(gDevice->device);
    }
    free(gDevice);
}
References privateAudioDevice::audioEnabled, privateAudioDevice::device, freeAudio(), gDevice, pauseAudio(), and privateAudioDevice::want.
freeAudio()
void freeAudio (Audio * audio)
{
    Audio * temp;
    while(audio != NULL)
    {
        if(audio->free == 1)
        {
            SDL_FreeWAV(audio->bufferTrue);
        }
        temp = audio;
        audio = audio->next;
        free(temp);
    }
}
References sound::bufferTrue, sound::free, and sound::next.
Referenced by audioCallback(), and endAudio().
initAudio()
void initAudio (void)
{
    Audio * global;
    gDevice = (PrivateAudioDevice*)calloc(1, sizeof(PrivateAudioDevice));
    gSoundCount = 0;
    if(gDevice == NULL)
    {
        fprintf(stderr, "[%s: %d]Fatal Error: Memory c-allocation error\n", __FILE__, __LINE__);
        return;
    }
    gDevice->audioEnabled = 0;
    if(!(SDL_WasInit(SDL_INIT_AUDIO) & SDL_INIT_AUDIO))
    {
        fprintf(stderr, "[%s: %d]Error: SDL_INIT_AUDIO not initialized\n", __FILE__, __LINE__);
        return;
    }
    SDL_memset(&(gDevice->want), 0, sizeof(gDevice->want));
    (gDevice->want).freq = AUDIO_FREQUENCY;
    (gDevice->want).format = AUDIO_FORMAT;
    (gDevice->want).channels = AUDIO_CHANNELS;
    (gDevice->want).samples = AUDIO_SAMPLES;
    (gDevice->want).callback = audioCallback;
    (gDevice->want).userdata = calloc(1, sizeof(Audio));
    global = (Audio*)(gDevice->want).userdata;
    if(global == NULL)
    {
        fprintf(stderr, "[%s: %d]Error: Memory allocation error\n", __FILE__, __LINE__);
        return;
    }
    global->buffer = NULL;
    global->next = NULL;
    /* want.userdata = new; */
    if((gDevice->device = SDL_OpenAudioDevice(NULL, 0, &(gDevice->want), NULL, SDL_AUDIO_ALLOW_CHANGES)) == 0)
    {
        fprintf(stderr, "[%s: %d]Warning: failed to open audio device: %s\n", __FILE__, __LINE__, SDL_GetError());
    }
    else
    {
        /* Set audio device enabled global flag */
        gDevice->audioEnabled = 1;
        /* Unpause active audio stream */
        unpauseAudio();
    }
}
References AUDIO_CHANNELS, AUDIO_FORMAT, AUDIO_FREQUENCY, AUDIO_SAMPLES, audioCallback(), privateAudioDevice::audioEnabled, sound::buffer, privateAudioDevice::device, gDevice, gSoundCount, sound::next, SDL_AUDIO_ALLOW_CHANGES, unpauseAudio(), and privateAudioDevice::want.
pauseAudio()
void pauseAudio (void)
{
    if(gDevice->audioEnabled)
    {
        SDL_PauseAudioDevice(gDevice->device, 1);
    }
}
References privateAudioDevice::audioEnabled, privateAudioDevice::device, and gDevice.
Referenced by endAudio().
playAudio()
static void playAudio (const char * filename, Audio * audio, uint8_t loop, int volume) inline static
{
    Audio * news;
    /* Check if audio is enabled */
    if(!gDevice->audioEnabled)
    {
        return;
    }
    /* If sound, check if under max number of sounds allowed, else don't play */
    if(loop == 0)
    {
        if(gSoundCount >= AUDIO_MAX_SOUNDS)
        {
            return;
        }
        else
        {
            gSoundCount++;
        }
    }
    /* Load from filename or from Memory */
    if(filename != NULL)
    {
        /* Create new music sound with loop */
        news = createAudio(filename, loop, volume);
    }
    else if(audio != NULL)
    {
        news = (Audio*)malloc(sizeof(Audio));
        if(news == NULL)
        {
            fprintf(stderr, "[%s: %d]Fatal Error: Memory allocation error\n", __FILE__, __LINE__);
            return;
        }
        memcpy(news, audio, sizeof(Audio));
        news->volume = volume;
        news->loop = loop;
        news->free = 0;
    }
    else
    {
        fprintf(stderr, "[%s: %d]Warning: filename and Audio parameters NULL\n", __FILE__, __LINE__);
        return;
    }
    /* Lock callback function */
    SDL_LockAudioDevice(gDevice->device);
    if(loop == 1)
    {
        addMusic((Audio *) (gDevice->want).userdata, news);
    }
    else
    {
        addAudio((Audio *) (gDevice->want).userdata, news);
    }
    SDL_UnlockAudioDevice(gDevice->device);
}
References addAudio(), addMusic(), AUDIO_MAX_SOUNDS, privateAudioDevice::audioEnabled, createAudio(), privateAudioDevice::device, sound::free, gDevice, gSoundCount, sound::loop, sound::volume, and privateAudioDevice::want.
Referenced by playMusic(), playMusicFromMemory(), playSound(), and playSoundFromMemory().
playMusic()
void playMusic (const char * filename, int volume)
{
    playAudio(filename, NULL, 1, volume);
}
References playAudio().
playMusicFromMemory()
void playMusicFromMemory (Audio * audio, int volume)
{
    playAudio(NULL, audio, 1, volume);
}
References playAudio().
playSound()
void playSound (const char * filename, int volume)
{
    playAudio(filename, NULL, 0, volume);
}
References playAudio().
playSoundFromMemory()
void playSoundFromMemory (Audio * audio, int volume)
{
    playAudio(NULL, audio, 0, volume);
}
References playAudio().
unpauseAudio()
void unpauseAudio (void)
{
    if(gDevice->audioEnabled)
    {
        SDL_PauseAudioDevice(gDevice->device, 0);
    }
}
References privateAudioDevice::audioEnabled, privateAudioDevice::device, and gDevice.
Referenced by initAudio().
Variable Documentation
gDevice
PrivateAudioDevice* gDevice static
Referenced by endAudio(), initAudio(), pauseAudio(), playAudio(), and unpauseAudio().
gSoundCount
uint32_t gSoundCount static
Referenced by audioCallback(), initAudio(), and playAudio().