Chess: Menu Class Reference
Menu Class Reference abstract
#include <Menu.h>
Public Member Functions
Menu ()
void draw () override=0
void update (float ms) override=0
void addOption (const MenuOption &option, ButtonType buttonType)
const MenuOption & getMenuOption (ButtonType buttonType)
const std::unordered_map< ButtonType, MenuOption > & getMenuOptions () const
virtual void pressButton (const ButtonType &type) const =0
Public Member Functions inherited from Drawable
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual ~Updateable ()=default
Private Attributes
std::unordered_map< ButtonType, MenuOption > options { std::unordered_map<ButtonType, MenuOption>() }
Constructor & Destructor Documentation
Menu()
Menu::Menu () default
Member Function Documentation
addOption()
void Menu::addOption (const MenuOption & option, ButtonType buttonType)
{
  this->options.try_emplace(buttonType, option);
}
References options.
Referenced by MainMenu::MainMenu().
draw()
void Menu::draw () override pure virtual
Implements Drawable.
Implemented in MainMenu.
getMenuOption()
const MenuOption & Menu::getMenuOption (ButtonType buttonType)
{
  return this->options.at(buttonType);
}
References options.
Referenced by MainMenu::update().
getMenuOptions()
const std::unordered_map< ButtonType, MenuOption > & Menu::getMenuOptions () const
{
  return this->options;
}
References options.
Referenced by MainMenu::draw(), and MainMenu::update().
pressButton()
virtual void Menu::pressButton (const ButtonType & type) const pure virtual
Implemented in MainMenu.
update()
void Menu::update (float ms) override pure virtual
Implements Updateable.
Implemented in MainMenu.
Member Data Documentation
options
std::unordered_map<ButtonType, MenuOption> Menu::options { std::unordered_map<ButtonType, MenuOption>() } private
Referenced by addOption(), getMenuOption(), and getMenuOptions().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/include/graphics/Menu.h
/Users/runner/work/chess/chess/src/graphics/Menu.cpp