Chess: /Users/runner/work/chess/chess/src/util/util/custom-string.h File Reference
custom-string.h File Reference
#include <string>
#include <vector>
#include <cstddef>
Namespaces
namespace custom_string
Functions
std::vector< std::string > custom_string::split (const std::string &string, const std::string &delimiter)
constexpr auto stringHash (const char *string)
constexpr auto operator""_hash (const char *string, std::size_t)
Function Documentation
operator""_hash()
constexpr auto operator""_hash (const char * string, std::size_t) constexpr
{
  return stringHash(string);
}
References stringHash().
stringHash()
constexpr auto stringHash (const char * string) constexpr
{
  unsigned long long hash { 0 };
  unsigned long long counter { 0 };
  for (auto pointer { string }; *pointer; ++pointer, ++counter) {
    hash += *pointer << counter;
  }
  return hash;
}
Referenced by PlayingScreen::getSquare(), and operator""_hash().