Chess: App Class Reference
App Class Reference
#include <App.h>
Public Member Functions
App ()
std::shared_ptr< Screen > getScreen () const
void changeScreen (const std::shared_ptr< Screen > &screen)
void registerGame (const std::shared_ptr< Game > &game)
std::weak_ptr< Game > getGame () const
void run ()
void draw () override
void update (float ms) override
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Private Attributes
std::shared_ptr< Screen > activeScreen {nullptr}
std::shared_ptr< Game > game_ {nullptr}
std::string input {}
Constructor & Destructor Documentation
App()
App::App () default
Member Function Documentation
changeScreen()
void App::changeScreen (const std::shared_ptr< Screen > & screen)
{
  this->activeScreen->cleanup();
  this->activeScreen.reset();
  this->game_.reset();
  this->activeScreen = {screen};
}
References activeScreen, and game_.
Referenced by InGameMenu::pressButton(), and MainMenu::pressButton().
draw()
void App::draw () override virtual
Implements Drawable.
               {
  if (this->activeScreen != nullptr) {
    this->activeScreen->draw();
  }
}
References activeScreen.
Referenced by run().
getGame()
std::weak_ptr< Game > App::getGame () const
{
  if (this->game_ == nullptr) {
    if (const auto playingScreen{std::dynamic_pointer_cast<PlayingScreen>(this->activeScreen)}; nullptr != playingScreen) {
      return playingScreen->getGame();
    }
  }
  return this->game_;
}
References activeScreen, and game_.
Referenced by Game::update().
getScreen()
std::shared_ptr< Screen > App::getScreen () const
{
  return this->activeScreen;
}
References activeScreen.
registerGame()
void App::registerGame (const std::shared_ptr< Game > & game)
{
  this->game_ = {game};
}
References game_.
Referenced by Game::start().
run()
void App::run ()
              {
  graphics::createWindow(1920, 1080, "Chess");
  graphics::preloadBitmaps(paths::getImagesPath());
  graphics::setUserData(this);
  graphics::setDrawFunction(std::bind_front(&App::draw, this));
  graphics::setUpdateFunction(std::bind_front(&App::update, this));
  graphics::setCanvasSize(3200, 1900);
  graphics::setCanvasScaleMode(graphics::CANVAS_SCALE_FIT);
  graphics::setFont(paths::getFontsPath() + "typography-times.ttf");
  Rectangle::populateBrushes();
  this->activeScreen = {std::make_shared<OpeningScreen>()};
  graphics::startMessageLoop();
  graphics::destroyWindow();
}
References activeScreen, draw(), paths::getFontsPath(), paths::getImagesPath(), Rectangle::populateBrushes(), and update().
update()
void App::update (float ms) override virtual
Implements Updateable.
{
  if (this->activeScreen != nullptr) {
    this->activeScreen->update(ms);
  }
}
References activeScreen.
Referenced by run().
Member Data Documentation
activeScreen
std::shared_ptr<Screen> App::activeScreen {nullptr} private
Referenced by changeScreen(), draw(), getGame(), getScreen(), run(), and update().
game_
std::shared_ptr<Game> App::game_ {nullptr} private
Referenced by changeScreen(), getGame(), and registerGame().
input
std::string App::input {} private
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/src/App.h
/Users/runner/work/chess/chess/src/App.cpp