Chess: HUD Class Reference
HUD Class Reference
#include <HUD.h>
Public Member Functions
HUD ()
HUD (std::string message, std::pair< float, float > coordinates, size_t size)
void draw () override
void update (float ms) override
void updateText (std::string text)
const std::pair< float, float > & getCoordinates () const
size_t getSize () const
float getLength () const
void setTextBrush (Brush type)
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Private Attributes
std::string message {}
std::pair< float, float > coordinates {}
std::size_t size {}
Rectangle drawingArea { Rectangle() }
std::pair< bool, std::optional< std::string > > newMessage { std::make_pair(false, std::optional<std::string>()) }
Constructor & Destructor Documentation
HUD() [1/2]
HUD::HUD () default
HUD() [2/2]
HUD::HUD (std::string message, std::pair< float, float > coordinates, size_t size) explicit
    : message(std::move(message)), coordinates(std::move(coordinates)), size(size) {
  this->drawingArea.setHeight(static_cast<float>(this->size));
  this->drawingArea.setWidth(static_cast<float>(this->message.length() * this->size) / 2);
  this->drawingArea.setCenter(Point(this->coordinates.first, this->coordinates.second));
}
References drawingArea, Rectangle::setCenter(), Rectangle::setHeight(), and Rectangle::setWidth().
Member Function Documentation
draw()
void HUD::draw () override virtual
Implements Drawable.
               {
  graphics::drawText(this->coordinates.first, this->coordinates.second, static_cast<float>(this->size), this->message, this->drawingArea.getBrush());
}
References coordinates.
getCoordinates()
const std::pair< float, float > & HUD::getCoordinates () const
{
  return this->coordinates;
}
References coordinates.
Referenced by MenuOption::MenuOption().
getLength()
float HUD::getLength () const
{
  return static_cast<float>(this->message.length());
}
References message.
Referenced by MenuOption::MenuOption().
getSize()
size_t HUD::getSize () const
{
  return this->size;
}
References size.
Referenced by MenuOption::MenuOption().
setTextBrush()
void HUD::setTextBrush (Brush type)
{
  this->drawingArea.setBrush(type, Rectangle::colors.at(type));
}
References Rectangle::colors, drawingArea, and Rectangle::setBrush().
Referenced by MainMenu::createMenuOption(), and PawnCount::PawnCount().
update()
void HUD::update (float ms) override virtual
Implements Updateable.
{
  if (this->newMessage.first) {
    this->message = { *(this->newMessage.second) };
    this->newMessage = { std::make_pair(false, std::optional<std::string>()) };
  }
}
References message, and newMessage.
updateText()
void HUD::updateText (std::string text)
{
  this->newMessage = { std::make_pair(true, std::move(text)) };
}
References newMessage.
Member Data Documentation
coordinates
std::pair<float, float> HUD::coordinates {} private
Referenced by draw(), and getCoordinates().
drawingArea
Rectangle HUD::drawingArea { Rectangle() } private
Referenced by HUD(), and setTextBrush().
message
std::string HUD::message {} private
Referenced by getLength(), and update().
newMessage
std::pair<bool, std::optional<std::string> > HUD::newMessage { std::make_pair(false, std::optional<std::string>()) } private
Referenced by update(), and updateText().
size
std::size_t HUD::size {} private
Referenced by getSize().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/include/hud/HUD.h
/Users/runner/work/chess/chess/src/hud/HUD.cpp