Chess: graphics::TextureManager Class Reference
graphics::TextureManager Class Reference
#include <texture.h>
Public Member Functions
GLuint getTexture (std::string file)
Private Attributes
std::unordered_map< std::string, Texture > textures
Member Function Documentation
getTexture()
GLuint graphics::TextureManager::getTexture (std::string file)
{
  auto iter = textures.find(file);
  if (iter != textures.end())
  {
    return iter->second.getID();
  }
  else
  {
    std::pair<std::string, Texture> texinfo = std::make_pair(file, Texture(file));
    textures.insert(texinfo);
    return texinfo.second.getID();
  }
}
Referenced by graphics::GLBackend::drawRect(), graphics::GLBackend::drawSector(), and graphics::GLBackend::preloadBitmaps().
Member Data Documentation
textures
std::unordered_map<std::string, Texture> graphics::TextureManager::textures private
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/include/sgg/sgg/texture.h
/Users/runner/work/chess/chess/include/sgg/sgg/texture.cpp