Chess: King Class Reference
King Class Reference
#include <King.h>
Public Member Functions
King (PawnColor color)
std::vector< std::pair< int, int > > getAdvanceableSquares () override
std::vector< std::pair< int, int > > getAdvanceableSquares (const std::vector< std::pair< int, int > > &steps, unsigned short int maxSteps, bool holding) const override
std::vector< std::pair< int, int > > getHoldingSquares () override
std::vector< std::pair< int, int > > getKingSquares (std::vector< std::pair< int, int > > &pairs) const
bool isChecked () const
std::vector< std::pair< int, int > > castle ()
void setMoved ()
void setRookMoved (int column)
bool moved () const
Public Member Functions inherited from Pawn
Pawn (PawnColor color)
void setSquare (const std::shared_ptr< Square > &square)
void capture (const std::shared_ptr< Pawn > &pawn)
std::weak_ptr< Square > getSquare () const
PawnColor getColor () const
void setTexture (std::string texture)
const std::string & getTexture () const
std::weak_ptr< Rectangle > getDrawingArea () const
void draw () override
void update (float ms) override
void move (float ms) override
void moveTo (const std::shared_ptr< Square > &squarePtr, const std::shared_ptr< Pawn > &self)
virtual std::vector< std::pair< int, int > > getAdvanceableSquares ()=0
virtual std::vector< std::pair< int, int > > getHoldingSquares ()=0
virtual std::vector< std::pair< int, int > > getAdvanceableSquares (const std::vector< pair > &steps, unsigned short int maxSteps, bool holding) const
std::vector< std::pair< int, int > > correctDirection (std::vector< std::pair< int, int > > steps) const
virtual std::weak_ptr< Pawn > getBlockedPawn ()
std::weak_ptr< Pawn > getBlockingPawn ()
bool isBlocked () const
void block ()
void unblock ()
void blockedBy (const std::shared_ptr< Pawn > &blocking)
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Public Member Functions inherited from Movable
Movable ()=default
virtual void move (float ms)=0
virtual ~Movable ()=default
Private Attributes
std::vector< std::pair< int, int > > steps_ {std::vector<std::pair<int, int>>()}
bool hasMoved {false}
bool rightRookHasMoved {false}
bool leftRookHasMoved {false}
Static Private Attributes
static constexpr unsigned short int maxSteps_ {1}
Constructor & Destructor Documentation
King()
King::King (PawnColor color) explicit
                          : Pawn(color) {
  Pawn::setTexture("king");
  this->steps_.push_back(std::make_pair<int, int>(1, 1));
  this->steps_.push_back(std::make_pair<int, int>(-1, 1));
  this->steps_.push_back(std::make_pair<int, int>(1, -1));
  this->steps_.push_back(std::make_pair<int, int>(-1, -1));
  this->steps_.push_back(std::make_pair<int, int>(1, 0));
  this->steps_.push_back(std::make_pair<int, int>(-1, 0));
  this->steps_.push_back(std::make_pair<int, int>(0, 1));
  this->steps_.push_back(std::make_pair<int, int>(0, -1));
}
References Pawn::setTexture(), and steps_.
Member Function Documentation
castle()
std::vector< std::pair< int, int > > King::castle ()
{
  auto castlingMoves{std::vector<std::pair<int, int>>()};
  if (!this->hasMoved) {
    const auto checkboard{static_cast<App *>(graphics::getUserData())
                              ->getGame()
                              .lock()
                              ->getCheckboard()};
    if (!this->leftRookHasMoved) {
      const auto nextLeftSquare{std::make_pair(Pawn::getSquare().lock()->getRow(), 3)};
      auto secondNextLeftSquare{std::make_pair(Pawn::getSquare().lock()->getRow(), 2)};
      const auto thirdNextLeftSquare{std::make_pair(Pawn::getSquare().lock()->getRow(), 1)};
      const bool nextEmptyAndSafe{(!checkboard->getSquare(nextLeftSquare).lock()->hasPawn()) && (0 == checkboard->getSquare(nextLeftSquare).lock()->getDangerReferenceCount(!Pawn::getColor()))};
      const bool secondNextEmptyAndSafe{(!checkboard->getSquare(secondNextLeftSquare).lock()->hasPawn()) && (0 == checkboard->getSquare(secondNextLeftSquare).lock()->getDangerReferenceCount(!Pawn::getColor()))};
      const bool thirdNextEmpty{!checkboard->getSquare(thirdNextLeftSquare).lock()->hasPawn()};
      if (nextEmptyAndSafe && secondNextEmptyAndSafe && thirdNextEmpty && (!this->isChecked())) {
        castlingMoves.emplace_back(secondNextLeftSquare);
      }
    }
    if (!this->rightRookHasMoved) {
      const auto nextRightSquare{std::make_pair(Pawn::getSquare().lock()->getRow(), 5)};
      auto secondNextRightSquare{std::make_pair(Pawn::getSquare().lock()->getRow(), 6)};
      const bool nextEmptyAndSafe{(!checkboard->getSquare(nextRightSquare).lock()->hasPawn()) && (0 == checkboard->getSquare(nextRightSquare).lock()->getDangerReferenceCount(!Pawn::getColor()))};
      const bool secondNextEmptyAndSafe{(!checkboard->getSquare(secondNextRightSquare).lock()->hasPawn()) && (0 == checkboard->getSquare(secondNextRightSquare).lock()->getDangerReferenceCount(!Pawn::getColor()))};
      if (nextEmptyAndSafe && secondNextEmptyAndSafe && (!this->isChecked())) {
        castlingMoves.emplace_back(secondNextRightSquare);
      }
    }
  }
  return castlingMoves;
}
References Pawn::getColor(), Pawn::getSquare(), hasMoved, isChecked(), leftRookHasMoved, and rightRookHasMoved.
Referenced by getAdvanceableSquares().
getAdvanceableSquares() [1/2]
std::vector< std::pair< int, int > > King::getAdvanceableSquares () override virtual
Implements Pawn.
{
  auto squares{Pawn::getAdvanceableSquares(this->steps_, King::maxSteps_, false)};
  auto kingSquares{this->getKingSquares(squares)};
  auto castlingSquares{this->castle()};
  kingSquares.insert(kingSquares.end(), castlingSquares.begin(), castlingSquares.end());
  return kingSquares;
}
References castle(), Pawn::getAdvanceableSquares(), getKingSquares(), maxSteps_, and steps_.
getAdvanceableSquares() [2/2]
std::vector< std::pair< int, int > > King::getAdvanceableSquares (const std::vector< std::pair< int, int > > & steps, unsigned short int maxSteps, bool holding) const override virtual
Reimplemented from Pawn.
getHoldingSquares()
std::vector< std::pair< int, int > > King::getHoldingSquares () override virtual
Implements Pawn.
{
  auto squares{Pawn::getAdvanceableSquares(this->steps_, King::maxSteps_, true)};
  return this->getKingSquares(squares);
}
References Pawn::getAdvanceableSquares(), getKingSquares(), maxSteps_, and steps_.
getKingSquares()
std::vector< std::pair< int, int > > King::getKingSquares (std::vector< std::pair< int, int > > & pairs) const
{
  auto checkboard{static_cast<App *>(graphics::getUserData())->getGame().lock()->getCheckboard()};
  std::erase_if(pairs, [this, &checkboard](const std::pair<int, int> &pair) {
    return checkboard->getSquare(pair).lock()->getDangerReferenceCount(!Pawn::getColor()) > 0;
  });
  auto enemyKing{checkboard->getKing(!Pawn::getColor())};
  auto enemyKingHoldingSquares{enemyKing.lock()->getAdvanceableSquares(this->steps_, King::maxSteps_, true)};
  std::erase_if(pairs, [&enemyKingHoldingSquares](const std::pair<int, int> &pair) {
    return std::ranges::find(enemyKingHoldingSquares, pair) != enemyKingHoldingSquares.end();
  });
  return pairs;
}
References Pawn::getColor(), maxSteps_, and steps_.
Referenced by getAdvanceableSquares(), and getHoldingSquares().
isChecked()
bool King::isChecked () const
{
  const PawnColor oppositeColor{!Pawn::getColor()};
  bool result;
  if (Pawn::getSquare().expired()) {
    result = {false};
  } else {
    result = {Pawn::getSquare().lock()->getDangerReferenceCount(oppositeColor) > 0};
  }
  return result;
}
References Pawn::getColor(), and Pawn::getSquare().
Referenced by castle().
moved()
bool King::moved () const
                       {
  return this->hasMoved;
}
References hasMoved.
setMoved()
void King::setMoved ()
                    {
  this->hasMoved = {true};
}
References hasMoved.
setRookMoved()
void King::setRookMoved (int column)
{
  if (0 == column) {
    this->leftRookHasMoved = {true};
  } else {
    this->rightRookHasMoved = {true};
  }
}
References leftRookHasMoved, and rightRookHasMoved.
Member Data Documentation
hasMoved
bool King::hasMoved {false} private
Referenced by castle(), moved(), and setMoved().
leftRookHasMoved
bool King::leftRookHasMoved {false} private
Referenced by castle(), and setRookMoved().
maxSteps_
constexpr unsigned short int King::maxSteps_ {1} static constexpr private
Referenced by getAdvanceableSquares(), getHoldingSquares(), and getKingSquares().
rightRookHasMoved
bool King::rightRookHasMoved {false} private
Referenced by castle(), and setRookMoved().
steps_
std::vector<std::pair<int, int> > King::steps_ {std::vector<std::pair<int, int>>()} private
Referenced by getAdvanceableSquares(), getHoldingSquares(), getKingSquares(), and King().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/src/game/game/King.h
/Users/runner/work/chess/chess/src/game/src/King.cpp