Chess: paths Namespace Reference
paths Namespace Reference
Functions
std::string getProjectRootPath ()
std::string getImagesPath ()
std::string getSoundsPath ()
std::string getFontsPath ()
Function Documentation
getFontsPath()
std::string paths::getFontsPath ()
{
  std::string root{paths::getProjectRootPath()};
  return std::filesystem::path(root + "/assets/fonts/", std::filesystem::path::native_format);
}
References getProjectRootPath().
Referenced by App::run().
getImagesPath()
std::string paths::getImagesPath ()
{
  std::string root{paths::getProjectRootPath()};
  return std::filesystem::path(root + "/assets/images/", std::filesystem::path::native_format);
}
References getProjectRootPath().
Referenced by PlayingScreen::getSquare(), App::run(), and Pawn::setSquare().
getProjectRootPath()
std::string paths::getProjectRootPath ()
{
  return std::filesystem::current_path().make_preferred().parent_path().parent_path().parent_path().parent_path();
}
Referenced by getFontsPath(), getImagesPath(), and getSoundsPath().
getSoundsPath()
std::string paths::getSoundsPath ()
{
  std::string root{paths::getProjectRootPath()};
  return std::filesystem::path(root + "/assets/sounds/", std::filesystem::path::native_format);
}
References getProjectRootPath().