Chess: Input handling
Input handling
Functions
void graphics::getMouseState (MouseState &ms)
bool graphics::getKeyState (scancode_t key)
Detailed Description
Function Documentation
getKeyState()
bool graphics::getKeyState (scancode_t key)
Polls the engine for the current state of a specific key.
Since buttons can be queried individually, multiple pressed keys can be detected, by querying each one of them. The function shall return true if a button has been reported as pressed by a window event between the previous call to the update function and the current call to getKeyState().
Parameters
key is the scancode ID of the key to query. The available scancodes are listed in the scancodes.h file.
Returns
true if the key is pressed, false otherwise.
See also
setUpdateFunction
  {
    return engine->getKeyState(key);
  }
References engine, and graphics::GLBackend::getKeyState().
getMouseState()
void graphics::getMouseState (MouseState & ms)
Polls the engine for the current state of the mouse.
Stores in the user-provided MouseState record ms, the current status of all mouse events. For more information on what data can be obtained, see the MouseState structure. Typically, this function is used from within the update callback of the application.
Parameters
ms is the user-provided record to update with the current status of the mouse cursor button and higher-level information such as mouse "dragging" and button "pressed / released".
See also
MouseState
setUpdateFunction
  {
    ms.dragging = engine->isMouseDragging();
    bool ba[3];
    engine->getMouseButtonState(ba);
    ms.button_left_down = ba[0];
    ms.button_middle_down = ba[1];
    ms.button_right_down = ba[2];
    engine->getMouseButtonPressed(ba);
    ms.button_left_pressed = ba[0];
    ms.button_middle_pressed = ba[1];
    ms.button_right_pressed = ba[2];
    engine->getMouseButtonReleased(ba);
    ms.button_left_released = ba[0];
    ms.button_middle_released = ba[1];
    ms.button_right_released = ba[2];
    int x, y;
    engine->getMousePosition(&x, &y);
    ms.cur_pos_x = x;
    ms.cur_pos_y = y;
    engine->getPrevMousePosition(&x, &y);
    ms.prev_pos_x = x;
    ms.prev_pos_y = y;
  }
References graphics::MouseState::button_left_down, graphics::MouseState::button_left_pressed, graphics::MouseState::button_left_released, graphics::MouseState::button_middle_down, graphics::MouseState::button_middle_pressed, graphics::MouseState::button_middle_released, graphics::MouseState::button_right_down, graphics::MouseState::button_right_pressed, graphics::MouseState::button_right_released, graphics::MouseState::cur_pos_x, graphics::MouseState::cur_pos_y, graphics::MouseState::dragging, engine, graphics::GLBackend::getMouseButtonPressed(), graphics::GLBackend::getMouseButtonReleased(), graphics::GLBackend::getMouseButtonState(), graphics::GLBackend::getMousePosition(), graphics::GLBackend::getPrevMousePosition(), graphics::GLBackend::isMouseDragging(), graphics::MouseState::prev_pos_x, and graphics::MouseState::prev_pos_y.
Referenced by Rectangle::clicked(), and Checkboard::update().