Chess: FontLib Class Reference
FontLib Class Reference
#include <fonts.h>
Public Member Functions
bool init ()
void submitText (const TextRecord &text)
void commitText ()
void setCanvas (glm::vec2 sz)
bool setCurrentFont (std::string fontname)
Private Member Functions
void drawText (TextRecord entry)
Private Attributes
std::unordered_map< std::string, Font >::iterator m_curr_font
std::unordered_map< std::string, Font > m_fonts
Shader m_font_shader
GLuint m_font_vbo
GLuint m_font_vao
GLuint m_font_res = 64
std::vector< TextRecord > m_content
glm::vec2 m_canvas
Static Private Attributes
static FT_Library m_ft = nullptr
Member Function Documentation
commitText()
void FontLib::commitText ()
{
  m_font_shader.use();
  glEnable(GL_SCISSOR_TEST);
  for (auto item : m_content)
  {
    drawText(item);
  }
  m_content.clear();
}
References drawText(), m_content, m_font_shader, and Shader::use().
Referenced by graphics::GLBackend::draw().
drawText()
void FontLib::drawText (TextRecord entry) private
{
  float x = 0.0f;
  float y = 0.0f;
  const char *p;
  if (!entry.font)
    return;
  Font font = *(entry.font);
  FT_GlyphSlot g = font.face->glyph;
#ifndef __APPLE__
  //glFrontFace(GL_CW);
#endif
  glEnable(GL_BLEND);
  glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
  glActiveTexture(GL_TEXTURE0);
  glBindTexture(GL_TEXTURE_2D, font.font_tex);
  static int c = 0;
  m_font_shader.use();
  m_font_shader["tex"] = 0;
  m_font_shader["color1"] = entry.color1;
  m_font_shader["color2"] = (entry.use_gradient? entry.color2 : entry.color1);
  m_font_shader["gradient"] = entry.gradient;
  m_font_shader["projection"] = entry.proj;
  for (p = entry.text.c_str(); *p; p++) {
    if (FT_Load_Char(font.face, *p, FT_LOAD_RENDER))
      continue;
    glTexImage2D(
      GL_TEXTURE_2D,
      0,
      GL_RED,
      g->bitmap.width,
      g->bitmap.rows,
      0,
      GL_RED,
      GL_UNSIGNED_BYTE,
      g->bitmap.buffer
      );
    float w = g->bitmap.width;
    float h = g->bitmap.rows;
    w = entry.size.x * g->bitmap.width / (float)m_font_res;
    h = entry.size.y * g->bitmap.rows / (float)m_font_res;
    float b = g->metrics.horiBearingY/(64* (float)m_font_res)*entry.size.y - h;
    GLfloat box[4][4] = {
      { x,     y-b    , 0, 1 },
      { x + w, y-b    , 1, 1 },
      { x,     y - h - b, 0, 0 },
      { x + w, y - h -b, 1, 0 },
    };
    m_font_shader["modelview"] = glm::translate(glm::vec3(entry.pos.x, entry.pos.y, 0.0f)) * entry.mv;
    sggBindVertexArray(m_font_vao);
    glBindBuffer(GL_ARRAY_BUFFER, m_font_vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof box, box, GL_DYNAMIC_DRAW);
    glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
    x += std::max(w+ entry.size.x*0.05f, entry.size.x*0.15f);
    y += entry.size.y*1.1f*(g->advance.y);
  }
  glBindTexture(GL_TEXTURE_2D, 0);
  glFrontFace(GL_CCW);
}
References TextRecord::color1, TextRecord::color2, Font::face, TextRecord::font, Font::font_tex, TextRecord::gradient, m_font_res, m_font_shader, m_font_vao, m_font_vbo, TextRecord::mv, TextRecord::pos, TextRecord::proj, sggBindVertexArray, TextRecord::size, TextRecord::text, Shader::use(), and TextRecord::use_gradient.
Referenced by commitText().
init()
bool FontLib::init ()
{
  if (FT_Init_FreeType(&m_ft))
  {
    return false;
  }
  glGetError();
  const GLubyte * s = glewGetErrorString(glGetError());
  m_font_shader = Shader(__FontVertexShader, __FontFragmentShader);
  if (!m_font_shader.init())
    return false;
  unsigned int attrib_position = m_font_shader.getAttributeLocation("coord");
  sggGenVertexArrays(1, &m_font_vao);
  sggBindVertexArray(m_font_vao);
  glGenBuffers(1, &m_font_vbo);
  glBindBuffer(GL_ARRAY_BUFFER, m_font_vbo);
  glEnableVertexAttribArray(attrib_position);
  glVertexAttribPointer(attrib_position, 4, GL_FLOAT, GL_FALSE, 0, 0);
  GLfloat box[4][4] = {
    { -1, 1    , 0, 0 },
    { 1, 1    , 1, 0 },
    { -1, -1, 0, 1 },
    { 1, -1, 1, 1 },
  };
  glBufferData(GL_ARRAY_BUFFER, sizeof box, box, GL_DYNAMIC_DRAW);
  m_curr_font = m_fonts.end();
  return true;
}
References __FontFragmentShader, __FontVertexShader, Shader::getAttributeLocation(), Shader::init(), m_curr_font, m_font_shader, m_font_vao, m_font_vbo, m_fonts, m_ft, sggBindVertexArray, and sggGenVertexArrays.
Referenced by graphics::GLBackend::init().
setCanvas()
void FontLib::setCanvas (glm::vec2 sz)
{
  m_canvas = sz;
}
References m_canvas.
Referenced by graphics::GLBackend::draw().
setCurrentFont()
bool FontLib::setCurrentFont (std::string fontname)
{
  m_curr_font = m_fonts.find(fontname);
  if (m_curr_font != m_fonts.end())
    return true;
  Font font;
  if (FT_New_Face(m_ft, fontname.c_str(), 0, &font.face))
  {
    return false;
  }
  FT_Set_Pixel_Sizes(font.face, 0, m_font_res);
  glActiveTexture(GL_TEXTURE0);
  glGenTextures(1, &font.font_tex);
  glBindTexture(GL_TEXTURE_2D, font.font_tex);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
  glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
  m_curr_font = m_fonts.insert(std::pair<std::string, Font>(fontname,font)).first;
  return true;
}
References Font::face, Font::font_tex, m_curr_font, m_font_res, m_fonts, and m_ft.
Referenced by graphics::GLBackend::setFont().
submitText()
void FontLib::submitText (const TextRecord & text)
{
  if (m_curr_font == m_fonts.end())
    return;
  // Not a very elegant workaround,
  // but helps keep changes minimal,
  // without a performance impact:
  const_cast<TextRecord&>(text).font = &(m_curr_font->second);
  m_content.push_back(text);
}
References m_content, m_curr_font, and m_fonts.
Referenced by graphics::GLBackend::drawText().
Member Data Documentation
m_canvas
glm::vec2 FontLib::m_canvas private
Referenced by setCanvas().
m_content
std::vector<TextRecord> FontLib::m_content private
Referenced by commitText(), and submitText().
m_curr_font
std::unordered_map<std::string,Font>::iterator FontLib::m_curr_font private
Referenced by init(), setCurrentFont(), and submitText().
m_font_res
GLuint FontLib::m_font_res = 64 private
Referenced by drawText(), and setCurrentFont().
m_font_shader
Shader FontLib::m_font_shader private
Referenced by commitText(), drawText(), and init().
m_font_vao
GLuint FontLib::m_font_vao private
Referenced by drawText(), and init().
m_font_vbo
GLuint FontLib::m_font_vbo private
Referenced by drawText(), and init().
m_fonts
std::unordered_map<std::string, Font> FontLib::m_fonts private
Referenced by init(), setCurrentFont(), and submitText().
m_ft
FT_Library FontLib::m_ft = nullptr static private
Referenced by init(), and setCurrentFont().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/include/sgg/sgg/fonts.h
/Users/runner/work/chess/chess/include/sgg/sgg/fonts.cpp