Chess: OpeningScreen Class Reference
OpeningScreen Class Reference
#include <OpeningScreen.h>
Public Member Functions
OpeningScreen ()
void draw () override
void update (float ms) override
void cleanup () override
Public Member Functions inherited from Screen
Screen ()
void draw () override=0
void update (float ms) override=0
virtual void cleanup ()=0
virtual ~Screen ()=default
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Private Attributes
std::unique_ptr< Menu > mainMenu = std::make_unique<MainMenu>()
std::unique_ptr< HUD > welcomeMessage {std::make_unique<HUD>()}
bool stopUpdating {false}
Constructor & Destructor Documentation
OpeningScreen()
OpeningScreen::OpeningScreen ()
{
  const std::string headline{"Let's play chess!"};
  const std::size_t size{180};
  const auto coordinates{std::make_pair(2400 - static_cast<float>(headline.length() * size) / 2, 480)};
  this->welcomeMessage = {std::make_unique<HUD>(headline, coordinates, size)};
  this->welcomeMessage->setTextBrush(Brush::DARK_BROWN);
}
References DARK_BROWN, and welcomeMessage.
Member Function Documentation
cleanup()
void OpeningScreen::cleanup () override virtual
Implements Screen.
{
  this->mainMenu.reset();
  this->welcomeMessage.reset();
  this->stopUpdating = {true};
}
References mainMenu, stopUpdating, and welcomeMessage.
draw()
void OpeningScreen::draw () override virtual
Implements Screen.
{
  if (!this->stopUpdating) {
    graphics::setWindowBackground(Rectangle::colors.at(Brush::LIGHT_BROWN));
    this->mainMenu->draw();
    this->welcomeMessage->draw();
  }
}
References Rectangle::colors, LIGHT_BROWN, mainMenu, stopUpdating, and welcomeMessage.
update()
void OpeningScreen::update (float ms) override virtual
Implements Screen.
{
  if (!this->stopUpdating) {
    this->mainMenu->update(ms);
  }
}
References mainMenu, and stopUpdating.
Member Data Documentation
mainMenu
std::unique_ptr<Menu> OpeningScreen::mainMenu = std::make_unique<MainMenu>() private
Referenced by cleanup(), draw(), and update().
stopUpdating
bool OpeningScreen::stopUpdating {false} private
Referenced by cleanup(), draw(), and update().
welcomeMessage
std::unique_ptr<HUD> OpeningScreen::welcomeMessage {std::make_unique<HUD>()} private
Referenced by cleanup(), draw(), and OpeningScreen().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/src/graphics/graphics/OpeningScreen.h
/Users/runner/work/chess/chess/src/graphics/src/OpeningScreen.cpp