Chess: Point Class Reference
Point Class Reference
#include <Point.h>
Public Member Functions
Point ()
Point (float x, float y)
float getX () const
float getY () const
Point operator+ (const Point &other) const
Private Attributes
float x {}
float y {}
Friends
bool operator== (const Point &lhs, const Point &rhs)=default
Constructor & Destructor Documentation
Point() [1/2]
Point::Point () default
Point() [2/2]
Point::Point (float x, float y)
: x(x), y(y) {}
Member Function Documentation
getX()
float Point::getX () const
{
  return this->x;
}
References x.
Referenced by Rectangle::clicked(), Rectangle::draw(), PlayingScreen::PlayingScreen(), Rectangle::Rectangle(), Rectangle::setCenter(), and Rectangle::setLeftBottom().
getY()
float Point::getY () const
{
  return this->y;
}
References y.
Referenced by Rectangle::clicked().
operator+()
Point Point::operator+ (const Point & other) const
{
  return {other.x + this->x, other.y + this->y};
}
References x, and y.
Friends And Related Function Documentation
operator==
bool operator== (const Point & lhs, const Point & rhs) friend
Member Data Documentation
x
float Point::x {} private
Referenced by getX(), and operator+().
y
float Point::y {} private
Referenced by getY(), and operator+().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/include/graphics/Point.h
/Users/runner/work/chess/chess/src/graphics/Point.cpp