Chess: Knight Class Reference
Knight Class Reference
#include <Knight.h>
Public Member Functions
Knight (PawnColor color)
std::vector< std::pair< int, int > > getAdvanceableSquares () override
std::vector< std::pair< int, int > > getHoldingSquares () override
Public Member Functions inherited from Pawn
Pawn (PawnColor color)
void setSquare (Square *square)
Square * getSquare () const
PawnColor getColor () const
void setTexture (std::string texture)
const std::string & getTexture () const
std::shared_ptr< Rectangle > getDrawingArea () const
void draw () override
void update (float ms) override
void move (float ms) override
void moveTo (Square *squarePtr, const std::shared_ptr< Pawn > &self)
virtual std::vector< std::pair< int, int > > getAdvanceableSquares ()=0
virtual std::vector< std::pair< int, int > > getHoldingSquares ()=0
virtual std::vector< std::pair< int, int > > getAdvanceableSquares (const std::vector< pair > &steps, unsigned short int maxSteps, bool holding) const
std::vector< std::pair< int, int > > correctDirection (std::vector< std::pair< int, int > > steps) const
virtual std::shared_ptr< Pawn > getBlockedPawn ()
std::shared_ptr< Pawn > getBlockingPawn ()
bool isBlocked () const
void block ()
void unblock ()
void blockedBy (const std::shared_ptr< Pawn > &blocking)
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Public Member Functions inherited from Movable
Movable ()=default
virtual void move (float ms)=0
virtual ~Movable ()=default
Private Attributes
std::vector< std::pair< int, int > > steps { std::vector<std::pair<int, int>>(static_cast<std::size_t>(8)) }
Static Private Attributes
static constexpr unsigned short int maxSteps { 1 }
Additional Inherited Members
Static Public Member Functions inherited from Pawn
static void capture (const std::shared_ptr< Pawn > &pawn)
Constructor & Destructor Documentation
Knight()
Knight::Knight (PawnColor color) explicit
                              : Pawn(color) {
  Pawn::setTexture("knight");
  this->steps.push_back(std::make_pair<int, int>(2, 1));
  this->steps.push_back(std::make_pair<int, int>(-2, 1));
  this->steps.push_back(std::make_pair<int, int>(2, -1));
  this->steps.push_back(std::make_pair<int, int>(-2, -1));
  this->steps.push_back(std::make_pair<int, int>(1, 2));
  this->steps.push_back(std::make_pair<int, int>(1, -2));
  this->steps.push_back(std::make_pair<int, int>(-1, 2));
  this->steps.push_back(std::make_pair<int, int>(-1, -2));
}
References Pawn::setTexture(), and steps.
Member Function Documentation
getAdvanceableSquares()
std::vector< std::pair< int, int > > Knight::getAdvanceableSquares () override virtual
Implements Pawn.
{
  return Pawn::getAdvanceableSquares(this->steps, Knight::maxSteps, false);
}
References Pawn::getAdvanceableSquares(), maxSteps, and steps.
getHoldingSquares()
std::vector< std::pair< int, int > > Knight::getHoldingSquares () override virtual
Implements Pawn.
{
  return Pawn::getAdvanceableSquares(this->steps, Knight::maxSteps, true);
}
References Pawn::getAdvanceableSquares(), maxSteps, and steps.
Member Data Documentation
maxSteps
constexpr unsigned short int Knight::maxSteps { 1 } static constexpr private
Referenced by getAdvanceableSquares(), and getHoldingSquares().
steps
std::vector<std::pair<int, int> > Knight::steps { std::vector<std::pair<int, int>>(static_cast<std::size_t>(8)) } private
Referenced by getAdvanceableSquares(), getHoldingSquares(), and Knight().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/include/game/Knight.h
/Users/runner/work/chess/chess/src/game/Knight.cpp