Chess: Square Class Reference
Square Class Reference
#include <Square.h>
Public Member Functions
Square ()
Square (unsigned short int row, unsigned short int column)
void initialize (Point leftBottom, const graphics::Brush &brush, Brush type, float squareWidth=100.0f)
unsigned short int getRow () const
unsigned short int getColumn () const
void setRow (unsigned short row)
void setColumn (unsigned short column)
char getColumnAsChar () const
void registerPawn (std::shared_ptr< Pawn > pawn)
void unregisterPawn ()
std::shared_ptr< Pawn > getPawn () const
bool hasPawn () const
Rectangle getDrawingArea () const
void draw () override
void update (float ms) override
void increaseDangerReferenceCount (PawnColor color)
void resetDangerReferenceCount ()
unsigned short int getDangerReferenceCount (PawnColor color) const
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Private Attributes
unsigned short int row_ { 0 }
unsigned short int column_ { 0 }
std::shared_ptr< Pawn > pawn_ { nullptr }
Rectangle drawingArea { Rectangle() }
unsigned short int whiteDangerReferenceCount_ { 0 }
unsigned short int blackDangerReferenceCount_ { 0 }
Friends
bool operator== (const Square &lhs, const Square &rhs)
Constructor & Destructor Documentation
Square() [1/2]
Square::Square () default
Square() [2/2]
Square::Square (unsigned short int row, unsigned short int column)
                                                                : row_(row), column_(column) {
  constexpr float offset { 400.0f };
  constexpr float squareWidth { 100.0f };
  const float reverseRowIndex { static_cast<float>(Checkboard::sideSize - 1 - this->row_) }; // coordinates start top left (0, 0) but checkboard row index start from bottom.
  this->drawingArea.setWidth(squareWidth);
  this->drawingArea.setHeight(squareWidth);
  this->drawingArea.setLeftBottom(Point(offset + squareWidth * static_cast<float>(this->column_), offset / 2 + squareWidth * reverseRowIndex));
  if ((this->column_ + this->row_) % 2 == 0) {
    this->drawingArea.setBrush(Brush::DARK_BROWN, Rectangle::colors.at(Brush::DARK_BROWN));
    this->drawingArea.setMarkBrush(Brush::DARK_GREEN);
  } else {
    this->drawingArea.setBrush(Brush::LIGHT_BROWN, Rectangle::colors.at(Brush::LIGHT_BROWN));
    this->drawingArea.setMarkBrush(Brush::LIGHT_GREEN);
  }
}
References Rectangle::colors, column_, DARK_BROWN, DARK_GREEN, drawingArea, LIGHT_BROWN, LIGHT_GREEN, row_, Rectangle::setBrush(), Rectangle::setHeight(), Rectangle::setLeftBottom(), Rectangle::setMarkBrush(), Rectangle::setWidth(), and Checkboard::sideSize.
Member Function Documentation
draw()
void Square::draw () override virtual
Implements Drawable.
                  {
  this->drawingArea.draw();
  if (this->hasPawn()) {
    this->pawn_->draw();
  }
}
References Rectangle::draw(), drawingArea, hasPawn(), and pawn_.
getColumn()
unsigned short int Square::getColumn () const
{ return this->column_; }
References column_.
Referenced by Pawn::getAdvanceableSquares(), Bishop::getBlockedPawn(), Queen::getBlockedPawn(), Rook::getBlockedPawn(), and Pawn::moveTo().
getColumnAsChar()
char Square::getColumnAsChar () const
{
  const char A = 'A';
  return static_cast<char>(A + static_cast<char>(this->column_));
}
References column_.
getDangerReferenceCount()
unsigned short int Square::getDangerReferenceCount (PawnColor color) const
{
  if (color == PawnColor::WHITE) {
    return this->whiteDangerReferenceCount_;
  } else {
    return this->blackDangerReferenceCount_;
  }
}
References blackDangerReferenceCount_, WHITE, and whiteDangerReferenceCount_.
getDrawingArea()
Rectangle Square::getDrawingArea () const
{
  return this->drawingArea;
}
References drawingArea.
Referenced by Pawn::move(), Checkboard::moveKing(), Checkboard::notify(), and Pawn::setSquare().
getPawn()
std::shared_ptr< Pawn > Square::getPawn () const
{
  return this->pawn_;
}
References pawn_.
Referenced by Checkboard::markSquares(), Pawn::move(), Checkboard::secureTheKing(), Checkboard::tryBlockCheck(), and Checkboard::tryMoveBlockedPawn().
getRow()
unsigned short int Square::getRow () const
{ return this->row_; }
References row_.
Referenced by Soldier::getAdvanceableSquares(), Pawn::getAdvanceableSquares(), Bishop::getBlockedPawn(), Queen::getBlockedPawn(), Rook::getBlockedPawn(), and Pawn::moveTo().
hasPawn()
bool Square::hasPawn () const
{
  return this->pawn_ != nullptr;
}
References pawn_.
Referenced by draw(), Checkboard::markSquares(), Pawn::move(), and update().
increaseDangerReferenceCount()
void Square::increaseDangerReferenceCount (PawnColor color)
{
  if (color == PawnColor::WHITE) {
    ++this->whiteDangerReferenceCount_;
  } else {
    ++this->blackDangerReferenceCount_;
  }
}
References blackDangerReferenceCount_, WHITE, and whiteDangerReferenceCount_.
initialize()
void Square::initialize (Point leftBottom, const graphics::Brush & brush, Brush type, float squareWidth = 100.0f)
{
  this->drawingArea.setWidth(squareWidth);
  this->drawingArea.setHeight(squareWidth);
  this->drawingArea.setLeftBottom(leftBottom);
  this->drawingArea.setBrush(type, brush);
}
References drawingArea, Rectangle::setBrush(), Rectangle::setHeight(), Rectangle::setLeftBottom(), and Rectangle::setWidth().
registerPawn()
void Square::registerPawn (std::shared_ptr< Pawn > pawn)
{
  this->pawn_ = { std::move(pawn) };
  this->pawn_->setSquare(this);
}
References pawn_.
Referenced by Pawn::move(), and Pawn::moveTo().
resetDangerReferenceCount()
void Square::resetDangerReferenceCount ()
{
  this->whiteDangerReferenceCount_ = { 0 };
  this->blackDangerReferenceCount_ = { 0 };
}
References blackDangerReferenceCount_, and whiteDangerReferenceCount_.
setColumn()
void Square::setColumn (unsigned short column)
{
  this->column_ = { column };
}
References column_.
Referenced by Pawn::moveTo().
setRow()
void Square::setRow (unsigned short row)
{
  this->row_ = { row };
}
References row_.
Referenced by Pawn::moveTo().
unregisterPawn()
void Square::unregisterPawn ()
{
  this->pawn_ = { nullptr };
}
References pawn_.
Referenced by Pawn::move().
update()
void Square::update (float ms) override virtual
Implements Updateable.
{
  if (this->hasPawn()) {
    this->pawn_->update(ms);
  }
  if (this->drawingArea.clicked()) {
    static_cast<App*>(graphics::getUserData())->getGame()->getCheckboard()->notify(this);
  }
  this->drawingArea.update(ms);
}
References Rectangle::clicked(), drawingArea, hasPawn(), pawn_, and Rectangle::update().
Friends And Related Function Documentation
operator==
bool operator== (const Square & lhs, const Square & rhs) friend
{
  return lhs.row_ == rhs.row_ && lhs.column_ == rhs.column_;
}
Member Data Documentation
blackDangerReferenceCount_
unsigned short int Square::blackDangerReferenceCount_ { 0 } private
Referenced by getDangerReferenceCount(), increaseDangerReferenceCount(), and resetDangerReferenceCount().
column_
unsigned short int Square::column_ { 0 } private
Referenced by getColumn(), getColumnAsChar(), setColumn(), and Square().
drawingArea
Rectangle Square::drawingArea { Rectangle() } private
Referenced by draw(), getDrawingArea(), initialize(), Square(), and update().
pawn_
std::shared_ptr<Pawn> Square::pawn_ { nullptr } private
Referenced by draw(), getPawn(), hasPawn(), registerPawn(), unregisterPawn(), and update().
row_
unsigned short int Square::row_ { 0 } private
Referenced by getRow(), setRow(), and Square().
whiteDangerReferenceCount_
unsigned short int Square::whiteDangerReferenceCount_ { 0 } private
Referenced by getDangerReferenceCount(), increaseDangerReferenceCount(), and resetDangerReferenceCount().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/include/game/Square.h
/Users/runner/work/chess/chess/src/game/Square.cpp