Chess: graphics::GLBackend Class Reference
graphics::GLBackend Class Reference
#include <GLbackend.h>
Public Member Functions
void drawRect (float cx, float cy, float w, float h, const struct Brush &brush)
void drawLine (float x_1, float y_1, float x_2, float y_2, const struct Brush &brush)
void drawSector (float cx, float cy, float start_angle, float end_angle, float radius1, float radius2, const struct Brush &brush)
void drawText (float pos_x, float pos_y, float size, const std::string &text, const Brush &brush)
void setUserData (const void *user_data)
void * getUserData ()
void setScale (float sx, float sy, float sz)
void setOrientation (float degrees)
void resetPose ()
bool setFont (std::string fontname)
std::vector< std::string > preloadBitmaps (std::string dir)
bool getKeyState (scancode_t key)
void setDrawCallback (std::function< void()> drf)
void setIdleCallback (std::function< void(float ms)> idf)
void setResizeCallback (std::function< void(int w, int h)> rsf)
virtual bool init ()
GLBackend (int w=800, int h=600, std::string title="")
virtual void cleanup ()
void swap ()
bool processMessages ()
virtual void update (float delta_time=0.0f)
virtual void resize (int w, int h)
float WindowToCanvasX (float x, bool clamped=true)
float WindowToCanvasY (float y, bool clamped=true)
virtual void draw ()
virtual ~GLBackend ()
void makeCurrent ()
void show (bool s)
void setBackgroundColor (float r, float g, float b)
float getDeltaTime ()
float getGlobalTime ()
void getMouseButtonPressed (bool *button_array)
void getMouseButtonReleased (bool *button_array)
void getMouseButtonState (bool *button_array)
void getMousePosition (int *x, int *y)
void getPrevMousePosition (int *x, int *y)
bool isMouseDragging ()
void setCanvasMode (int m)
void setCanvasSize (float w, float h)
void setFullscreen (bool fs)
void playSound (std::string soundfile, float volume, bool looping=false)
void playMusic (std::string soundfile, float volume, bool looping=true, int fade_time=0)
void stopMusic (int fade_time=0)
void terminate ()
Protected Member Functions
bool processEvent (SDL_Event event)
void advanceTime ()
void computeProjection ()
void initPrimitives ()
void computeTransformation ()
Protected Attributes
int m_width
int m_height
std::string m_title
SDL_Window * m_window
uint32_t m_windowID
SDL_GLContext m_context
bool m_initialized = false
FontLib m_fontlib
SDL_TimerID m_idle_timer
glm::vec3 m_back_color = { 0.0f, 0.0f, 0.0f }
bool m_quit = false
glm::ivec2 m_mouse_pos = glm::ivec2()
glm::ivec2 m_prev_mouse_pos = glm::ivec2()
bool m_button_state [3] = { 0, 0, 0 }
bool m_button_pressed [3] = { 0, 0, 0 }
bool m_button_released [3] = { 0, 0, 0 }
bool m_mouse_dragging = false
glm::vec4 m_requested_canvas = glm::vec4(0.0f)
glm::vec4 m_canvas
int m_canvas_mode = 0
glm::mat4 m_projection
glm::mat4 m_transformation = glm::mat4(1.0f)
float m_orientation = 0.0f
glm::vec3 m_scale = glm::vec3(1.0f)
Shader m_flat_shader
GLuint m_rect_vbo
GLuint m_rect_vao
GLuint m_rect_outline_vbo
GLuint m_rect_outline_vao
GLuint m_line_vbo
GLuint m_line_vao
GLuint m_sector_vbo
GLuint m_sector_vao
GLuint m_sector_outline_vbo
GLuint m_sector_outline_vao
glm::vec4 m_window_to_canvas_factors
AudioManager * m_audio = nullptr
TextureManager textures
std::chrono::time_point< std::chrono::steady_clock > m_prev_time_tick
float m_global_time = 0.0f
float m_delta_time = 0.0f
const void * m_user_data = nullptr
std::function< void()> m_draw_callback = nullptr
std::function< void(float ms)> m_idle_callback = nullptr
std::function< void(int w, int h)> m_resize_callback = nullptr
Constructor & Destructor Documentation
GLBackend()
graphics::GLBackend::GLBackend (int w = 800, int h = 600, std::string title = "")
                                                    :
    m_width(w), m_height(h), m_title(title),
    m_draw_callback(nullptr),
    m_resize_callback(nullptr),
    m_idle_callback(nullptr),
    m_prev_time_tick()
  {
  }
~GLBackend()
graphics::GLBackend::~GLBackend () virtual
  {
  }
Member Function Documentation
advanceTime()
void graphics::GLBackend::advanceTime () protected
  {
    auto now = std::chrono::steady_clock::now();
    std::chrono::duration<float> elapsed_seconds = now - m_prev_time_tick;
    m_delta_time = elapsed_seconds.count()*1000.0f;
    m_global_time += m_delta_time;
    m_prev_time_tick = now;
  }
References m_delta_time, m_global_time, and m_prev_time_tick.
Referenced by draw(), and processMessages().
cleanup()
void graphics::GLBackend::cleanup () virtual
  {
    SDL_GL_DeleteContext(m_context);
    SDL_DestroyWindow(m_window);
    if (m_audio)
      delete m_audio;
    SDL_Quit();
  }
References m_audio, m_context, and m_window.
Referenced by graphics::destroyWindow().
computeProjection()
void graphics::GLBackend::computeProjection () protected
  {
    float w, h;
    float n = -1.0f, f = 1.0f;
    float true_aspect = m_width / (float)m_height;
    float req_aspect = m_requested_canvas.z / m_requested_canvas.w;
    switch (m_canvas_mode)
    {
    case CANVAS_SCALE_STRETCH:
      m_canvas = m_requested_canvas;
      m_projection = glm::scale(glm::vec3(1, -1, 1)) * glm::ortho(0.0f, m_canvas.z, 0.0f, m_canvas.w, n, f);
      break;
    case CANVAS_SCALE_FIT:
      if (true_aspect > req_aspect)
      {
        m_canvas.z = (true_aspect / req_aspect) * m_requested_canvas.z;
        m_canvas.w = m_requested_canvas.w;
        m_canvas.x = -m_requested_canvas.z * (true_aspect / req_aspect-1.0f) / 2;
        m_canvas.y = 0.0f;
        m_canvas.z += m_canvas.x;
      }
      else
      {
        m_canvas.z = m_requested_canvas.z;
        m_canvas.w = (req_aspect / true_aspect) * m_requested_canvas.w;
        m_canvas.y = 0.0f;
        m_canvas.x = 0.0f;
        m_canvas.y = -m_requested_canvas.w * (req_aspect / true_aspect - 1.0f) / 2;
        m_canvas.w += m_canvas.y;
      }
      m_projection = glm::scale(glm::vec3(1, -1, 1)) * glm::ortho(m_canvas.x, m_canvas.z, m_canvas.y, m_canvas.w, n, f);
      break;
    default:
      m_canvas = glm::vec4(0.0f, 0.0f, (float)m_width, (float)m_height);
      m_projection = glm::scale(glm::vec3(1, -1, 1)) * glm::ortho(0.0f, m_canvas.z, 0.0f, m_canvas.w, n, f);
    }
  }
References graphics::CANVAS_SCALE_FIT, graphics::CANVAS_SCALE_STRETCH, m_canvas, m_canvas_mode, m_height, m_projection, m_requested_canvas, and m_width.
Referenced by init(), and resize().
computeTransformation()
void graphics::GLBackend::computeTransformation () protected
  {
    // note: rotation is CW, due to mirroring after projection.
    m_transformation = glm::rotate(-3.1415936f*m_orientation / 180.0f, glm::vec3(0.f, 0.f, 1.f)) * glm::scale(m_scale);
  }
References m_orientation, m_scale, and m_transformation.
Referenced by setOrientation(), and setScale().
draw()
void graphics::GLBackend::draw () virtual
  {
    m_flat_shader.use();
    // reset timers on first run
    static bool first_time = true;
    if (first_time)
    {
      advanceTime();
      m_global_time = 0.0f;
      m_delta_time = 0.0f;
      first_time = false;
      //force a call to resize to take canvas parameters set by the user.
      resize(m_width, m_height);
      return;
    }
    resetPose();
    glDepthMask(0.0f);
    glDisable(GL_DEPTH_TEST);
    glClearColor(0.0f, 0.0f, 0.f, 1.0);
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
    if (m_canvas_mode == CANVAS_SCALE_FIT)
    {
      float true_aspect = m_width / (float)m_height;
      float req_aspect = m_requested_canvas.z / m_requested_canvas.w;
      glEnable(GL_SCISSOR_TEST);
      glm::vec4 rect;
      rect.x = (true_aspect > req_aspect ? (m_width - m_height * req_aspect) / 2.0f : 0.0f);
      rect.y = (req_aspect > true_aspect ? (m_height - m_width / req_aspect)/2.0f : 0.0f);
      rect.z = (true_aspect > req_aspect ? m_height * req_aspect : m_width);
      rect.w = (req_aspect > true_aspect ? m_width / req_aspect : m_height);
      glScissor(rect.x, rect.y, rect.z, rect.w);
    }
    Brush bck;
    bck.fill_color[0] = m_back_color.r, bck.fill_color[1] = m_back_color.g, bck.fill_color[2] = m_back_color.b;
    bck.outline_opacity = 0.0f;
    drawRect(m_requested_canvas.z / 2, m_requested_canvas.w / 2, m_requested_canvas.z, m_requested_canvas.w, bck);
    glEnable(GL_BLEND);
    glBlendEquation(GL_ADD);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    m_flat_shader["P"] = m_projection;
    glGetError();
    if (m_draw_callback != nullptr)
      m_draw_callback();
    m_fontlib.setCanvas(glm::vec2(m_requested_canvas.z, m_requested_canvas.w));
    m_fontlib.commitText();
    glDisable(GL_SCISSOR_TEST);
    swap();
  }
References advanceTime(), graphics::CANVAS_SCALE_FIT, FontLib::commitText(), drawRect(), graphics::Brush::fill_color, m_back_color, m_canvas_mode, m_delta_time, m_draw_callback, m_flat_shader, m_fontlib, m_global_time, m_height, m_projection, m_requested_canvas, m_width, graphics::Brush::outline_opacity, resetPose(), resize(), FontLib::setCanvas(), swap(), and Shader::use().
Referenced by processMessages(), resize(), and graphics::startMessageLoop().
drawLine()
void graphics::GLBackend::drawLine (float x_1, float y_1, float x_2, float y_2, const struct Brush & brush)
  {
    m_flat_shader["color1"] = glm::vec4(brush.outline_color[0], brush.outline_color[1], brush.outline_color[2], brush.outline_opacity);
    m_flat_shader["MV"] = glm::mat4(1.0f);
    m_flat_shader["gradient"] = glm::vec2(1.0f, 0.0f);
    GLfloat line[2][4] =
    {
      { x_1, y_1, 0.0f, 1.0f},
      { x_2, y_2, 0.1f, 1.0f},
    };
    sggBindVertexArray(m_line_vao);
    glBindBuffer(GL_ARRAY_BUFFER, m_line_vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof line, line, GL_DYNAMIC_DRAW);
    unsigned int attrib_flat_position = m_flat_shader.getAttributeLocation("coord");
    glEnableVertexAttribArray(attrib_flat_position);
    glVertexAttribPointer(attrib_flat_position, 4, GL_FLOAT, GL_FALSE, 0, 0);
    glDrawArrays(GL_LINES, 0, 2);
  }
References Shader::getAttributeLocation(), m_flat_shader, m_line_vao, m_line_vbo, graphics::Brush::outline_color, graphics::Brush::outline_opacity, and sggBindVertexArray.
Referenced by graphics::drawLine().
drawRect()
void graphics::GLBackend::drawRect (float cx, float cy, float w, float h, const struct Brush & brush)
  {
    glEnable(GL_TEXTURE_2D);
    glFrontFace(GL_CCW);
    glPolygonMode(GL_FRONT, GL_FILL);
    glm::mat4 mat = glm::translate(glm::vec3(cx, cy, 0.0f)) *
      m_transformation * glm::scale(glm::vec3(w, h, 1.0f));
    m_flat_shader["gradient"] = glm::vec2(brush.gradient_dir_u, brush.gradient_dir_v);
    // fill
    if (brush.fill_opacity != 0.0f || brush.fill_secondary_opacity != 0.0f )
    {
      int tid = textures.getTexture(brush.texture);
      if (tid > 0)
      {
        glActiveTexture(GL_TEXTURE0);
        glBindTexture(GL_TEXTURE_2D, tid);
      }
      m_flat_shader["color1"] = glm::vec4(brush.fill_color[0], brush.fill_color[1], brush.fill_color[2], brush.fill_opacity);
      if (brush.gradient)
      {
        m_flat_shader["color2"] = glm::vec4(brush.fill_secondary_color[0], brush.fill_secondary_color[1],
          brush.fill_secondary_color[2], brush.fill_secondary_opacity);
      }
      else
      {
        m_flat_shader["color2"] = glm::vec4(brush.fill_color[0], brush.fill_color[1], brush.fill_color[2], brush.fill_opacity);
      }
      m_flat_shader["MV"] = mat;
      m_flat_shader["tex"] = 0;
      if (tid>0)
        m_flat_shader["has_texture"] = 1;
      else
        m_flat_shader["has_texture"] = 0;
      unsigned int attrib_flat_position = m_flat_shader.getAttributeLocation("coord");
      sggBindVertexArray(m_rect_vao);
      glBindBuffer(GL_ARRAY_BUFFER, m_rect_vbo);
      glEnableVertexAttribArray(attrib_flat_position);
      glVertexAttribPointer(attrib_flat_position, 4, GL_FLOAT, GL_FALSE, 0, 0);
      glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
    }
    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, 0);
    if (brush.outline_opacity>0.0f)
    {
      m_flat_shader.use();
      m_flat_shader["color1"] = glm::vec4(brush.outline_color[0], brush.outline_color[1], brush.outline_color[2], brush.outline_opacity);
      m_flat_shader["color2"] = glm::vec4(brush.outline_color[0], brush.outline_color[1], brush.outline_color[2], brush.outline_opacity);
      m_flat_shader["MV"] = mat;
      m_flat_shader["has_texture"] = 0;
      glLineWidth(brush.outline_width);
      sggBindVertexArray(m_rect_outline_vao);
      glBindBuffer(GL_ARRAY_BUFFER, m_rect_outline_vbo);
      unsigned int attrib_flat_position = m_flat_shader.getAttributeLocation("coord");
      glEnableVertexAttribArray(attrib_flat_position);
      glVertexAttribPointer(attrib_flat_position, 4, GL_FLOAT, GL_FALSE, 0, 0);
      glDrawArrays(GL_LINE_LOOP, 0, 4);
      glLineWidth(1);
    }
  }
References graphics::Brush::fill_color, graphics::Brush::fill_opacity, graphics::Brush::fill_secondary_color, graphics::Brush::fill_secondary_opacity, Shader::getAttributeLocation(), graphics::TextureManager::getTexture(), graphics::Brush::gradient, graphics::Brush::gradient_dir_u, graphics::Brush::gradient_dir_v, m_flat_shader, m_rect_outline_vao, m_rect_outline_vbo, m_rect_vao, m_rect_vbo, m_transformation, graphics::Brush::outline_color, graphics::Brush::outline_opacity, graphics::Brush::outline_width, sggBindVertexArray, graphics::Brush::texture, textures, and Shader::use().
Referenced by draw(), and graphics::drawRect().
drawSector()
void graphics::GLBackend::drawSector (float cx, float cy, float start_angle, float end_angle, float radius1, float radius2, const struct Brush & brush)
  {
    glEnable(GL_TEXTURE_2D);
    glFrontFace(GL_CCW);
    glPolygonMode(GL_FRONT, GL_FILL);
    m_flat_shader["MV"] = glm::translate(glm::vec3(cx, cy, 0.0f)) * m_transformation;
    m_flat_shader["gradient"] = glm::vec2(brush.gradient_dir_u,brush.gradient_dir_v);
    float sector_vertices[2 * CURVE_SUBDIVS+2][4];
    float sector_outline_vertices[2 * CURVE_SUBDIVS+2][4];
    float r1 = radius1, r2 = radius2;
    float arc_inc = 3.1415936f*(end_angle - start_angle) / (180.0f*CURVE_SUBDIVS);
    for (int i = 0; i <= CURVE_SUBDIVS; i++)
    {
      float s = i / (float)CURVE_SUBDIVS;
      sector_vertices[i * 2 + 0][0] = r1 * cos(3.1415936f*start_angle / 180.f + i * arc_inc);
      sector_vertices[i * 2 + 0][1] = r1 * -sin(3.1415936f*start_angle / 180.f + i * arc_inc);
      sector_vertices[i * 2 + 0][2] = s;
      sector_vertices[i * 2 + 0][3] = 0.0f;
      sector_vertices[i * 2 + 1][0] = r2 * cos(3.1415936f*start_angle / 180.f + i * arc_inc);
      sector_vertices[i * 2 + 1][1] = r2 * -sin(3.1415936f*start_angle / 180.f + i * arc_inc);
      sector_vertices[i * 2 + 1][2] = s;
      sector_vertices[i * 2 + 1][3] = 1.0f;
    }
    for (int i = 0; i <= CURVE_SUBDIVS; i++)
    {
      float s = i / (float)CURVE_SUBDIVS;
      sector_outline_vertices[i][0] = r1 * cos(3.1415936f*start_angle / 180.f + i * arc_inc);
      sector_outline_vertices[i][1] = r1 * -sin(3.1415936f*start_angle / 180.f + i * arc_inc);
      sector_outline_vertices[i][2] = s;
      sector_outline_vertices[i][3] = 0.0f;
    }
    for (int i = CURVE_SUBDIVS; i >= 0; i--)
    {
      float s = (i) / (float)CURVE_SUBDIVS;
      sector_outline_vertices[2*CURVE_SUBDIVS-i+1][0] = r2 * cos(3.1415936f*start_angle / 180.f + i * arc_inc);
      sector_outline_vertices[2*CURVE_SUBDIVS-i+1][1] = r2 * -sin(3.1415936f*start_angle / 180.f + i * arc_inc);
      sector_outline_vertices[2*CURVE_SUBDIVS-i+1][2] = s;
      sector_outline_vertices[2*CURVE_SUBDIVS-i+1][3] = 1.0f;
    }
    // fill
    if (brush.fill_opacity != 0.0f || brush.fill_secondary_opacity != 0.0f)
    {
      int tid = textures.getTexture(brush.texture);
      if (tid > 0)
      {
        glActiveTexture(GL_TEXTURE0);
        glBindTexture(GL_TEXTURE_2D, tid);
      }
      m_flat_shader["color1"] = glm::vec4(brush.fill_color[0], brush.fill_color[1], brush.fill_color[2], brush.fill_opacity);
      if (brush.gradient)
      {
        m_flat_shader["color2"] = glm::vec4(brush.fill_secondary_color[0], brush.fill_secondary_color[1],
          brush.fill_secondary_color[2], brush.fill_secondary_opacity);
      }
      else
      {
        m_flat_shader["color2"] = glm::vec4(brush.fill_color[0], brush.fill_color[1], brush.fill_color[2], brush.fill_opacity);
      }
      m_flat_shader["tex"] = 0;
      if (tid > 0)
        m_flat_shader["has_texture"] = 1;
      else
        m_flat_shader["has_texture"] = 0;
      sggBindVertexArray(m_sector_vao);
      glBindBuffer(GL_ARRAY_BUFFER, m_sector_vbo);
      glBufferData(GL_ARRAY_BUFFER, sizeof sector_vertices, sector_vertices, GL_DYNAMIC_DRAW);
      unsigned int attrib_flat_position = m_flat_shader.getAttributeLocation("coord");
      glEnableVertexAttribArray(attrib_flat_position);
      glVertexAttribPointer(attrib_flat_position, 4, GL_FLOAT, GL_FALSE, 0, 0);
      glDrawArrays(GL_TRIANGLE_STRIP, 0, 2 * CURVE_SUBDIVS+2);
    }
    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, 0);
    if (brush.outline_opacity > 0.0f)
    {
      m_flat_shader.use();
      m_flat_shader["color1"] = glm::vec4(brush.outline_color[0], brush.outline_color[1], brush.outline_color[2], brush.outline_opacity);
      m_flat_shader["color2"] = glm::vec4(brush.outline_color[0], brush.outline_color[1], brush.outline_color[2], brush.outline_opacity);
      m_flat_shader["has_texture"] = 0;
      glLineWidth(brush.outline_width);
      sggBindVertexArray(m_sector_outline_vao);
      glBindBuffer(GL_ARRAY_BUFFER, m_sector_outline_vbo);
      glBufferData(GL_ARRAY_BUFFER, sizeof sector_outline_vertices, sector_outline_vertices, GL_DYNAMIC_DRAW);
      unsigned int attrib_flat_position = m_flat_shader.getAttributeLocation("coord");
      glEnableVertexAttribArray(attrib_flat_position);
      glVertexAttribPointer(attrib_flat_position, 4, GL_FLOAT, GL_FALSE, 0, 0);
      if (fabs(end_angle-start_angle-360.0f)>0.000f)
        glDrawArrays(GL_LINE_LOOP, 0, 2 * CURVE_SUBDIVS+2);
      else
        glDrawArrays(GL_LINE_LOOP, CURVE_SUBDIVS + 1, CURVE_SUBDIVS );
      glLineWidth(1);
    }
  }
References CURVE_SUBDIVS, graphics::Brush::fill_color, graphics::Brush::fill_opacity, graphics::Brush::fill_secondary_color, graphics::Brush::fill_secondary_opacity, Shader::getAttributeLocation(), graphics::TextureManager::getTexture(), graphics::Brush::gradient, graphics::Brush::gradient_dir_u, graphics::Brush::gradient_dir_v, m_flat_shader, m_sector_outline_vao, m_sector_outline_vbo, m_sector_vao, m_sector_vbo, m_transformation, graphics::Brush::outline_color, graphics::Brush::outline_opacity, graphics::Brush::outline_width, sggBindVertexArray, graphics::Brush::texture, textures, and Shader::use().
Referenced by graphics::drawDisk(), and graphics::drawSector().
drawText()
void graphics::GLBackend::drawText (float pos_x, float pos_y, float size, const std::string & text, const Brush & brush)
  {
    TextRecord entry;
    entry.text = text;
    entry.pos = glm::vec2(pos_x, pos_y);
    entry.size = glm::vec2(size, size);
    entry.color1 = glm::vec4(brush.fill_color[0], brush.fill_color[1], brush.fill_color[2], brush.fill_opacity);
    entry.color2 = glm::vec4(brush.fill_secondary_color[0], brush.fill_secondary_color[1], brush.fill_secondary_color[2], brush.fill_secondary_opacity);
    entry.gradient = glm::vec2(brush.gradient_dir_u, brush.gradient_dir_v);
    entry.use_gradient = brush.gradient;
    entry.mv = m_transformation;
    entry.proj = m_projection;
    m_fontlib.submitText(entry);
  }
References TextRecord::color1, TextRecord::color2, graphics::Brush::fill_color, graphics::Brush::fill_opacity, graphics::Brush::fill_secondary_color, graphics::Brush::fill_secondary_opacity, TextRecord::gradient, graphics::Brush::gradient, graphics::Brush::gradient_dir_u, graphics::Brush::gradient_dir_v, m_fontlib, m_projection, m_transformation, TextRecord::mv, TextRecord::pos, TextRecord::proj, TextRecord::size, FontLib::submitText(), TextRecord::text, and TextRecord::use_gradient.
Referenced by graphics::drawText().
getDeltaTime()
float graphics::GLBackend::getDeltaTime ()
  {
    return m_delta_time;
  }
References m_delta_time.
Referenced by graphics::getDeltaTime(), and processMessages().
getGlobalTime()
float graphics::GLBackend::getGlobalTime ()
  {
    return m_global_time;
  }
References m_global_time.
Referenced by graphics::getGlobalTime().
getKeyState()
bool graphics::GLBackend::getKeyState (scancode_t key)
  {
    int numkeys;
    const uint8_t * keymap = SDL_GetKeyboardState(&numkeys);
    return keymap[key];
  }
Referenced by graphics::getKeyState().
getMouseButtonPressed()
void graphics::GLBackend::getMouseButtonPressed (bool * button_array)
  {
    button_array[0] = m_button_pressed[0];
    button_array[1] = m_button_pressed[1];
    button_array[2] = m_button_pressed[2];
  }
References m_button_pressed.
Referenced by graphics::getMouseState().
getMouseButtonReleased()
void graphics::GLBackend::getMouseButtonReleased (bool * button_array)
  {
    button_array[0] = m_button_released[0];
    button_array[1] = m_button_released[1];
    button_array[2] = m_button_released[2];
  }
References m_button_released.
Referenced by graphics::getMouseState().
getMouseButtonState()
void graphics::GLBackend::getMouseButtonState (bool * button_array)
  {
    button_array[0] = m_button_state[0];
    button_array[1] = m_button_state[1];
    button_array[2] = m_button_state[2];
  }
References m_button_state.
Referenced by graphics::getMouseState().
getMousePosition()
void graphics::GLBackend::getMousePosition (int * x, int * y)
  {
    *x = m_mouse_pos.x;
    *y = m_mouse_pos.y;
  }
References m_mouse_pos.
Referenced by graphics::getMouseState().
getPrevMousePosition()
void graphics::GLBackend::getPrevMousePosition (int * x, int * y)
  {
    *x = m_prev_mouse_pos.x;
    *y = m_prev_mouse_pos.y;
  }
References m_prev_mouse_pos.
Referenced by graphics::getMouseState().
getUserData()
void * graphics::GLBackend::getUserData ()
{
    /* Safely cast const away */
    return const_cast<void*>(m_user_data);
  }
References m_user_data.
Referenced by graphics::getUserData().
init()
bool graphics::GLBackend::init () virtual
  {
    m_initialized = false;
    if (SDL_Init(SDL_INIT_VIDEO | SDL_INIT_TIMER | SDL_INIT_EVENTS | SDL_INIT_AUDIO) < 0)
    {
      std::cout << "Failed to init SDL\n";
      return false;
    }
    m_window = SDL_CreateWindow(m_title.c_str(), SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
      m_width, m_height, SDL_WINDOW_SHOWN | SDL_WINDOW_OPENGL | SDL_WINDOW_RESIZABLE );
    m_windowID = SDL_GetWindowID(m_window);
    m_audio = new AudioManager();
    if (!m_window)
    {
      std::cout << "Unable to create window\n";
      CheckSDLError(__LINE__);
      return false;
    }
    m_context = SDL_GL_CreateContext(m_window);
    //SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES, 4);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
    SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 0);
    SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, 1);
    SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, 8);
    SDL_GL_SetSwapInterval(0);
    glewExperimental = GL_TRUE;
    glewInit();
    glGetError();
    glEnable(GL_DEPTH_TEST);
    glDepthFunc(GL_LEQUAL);
    glClearDepth(1.0f);
    glDisable(GL_CULL_FACE);
    glCullFace(GL_BACK);
    if (!m_fontlib.init())
    {
      std::cout << "Unable to initialize font library\n";
      CheckSDLError(__LINE__);
      return false;
    }
    initPrimitives();
    computeProjection();
    glViewport(0, 0, m_width, m_height);
    m_initialized = true;
    return true;
  }
References graphics::CheckSDLError(), computeProjection(), FontLib::init(), initPrimitives(), m_audio, m_context, m_fontlib, m_height, m_initialized, m_title, m_width, m_window, and m_windowID.
Referenced by graphics::createWindow().
initPrimitives()
void graphics::GLBackend::initPrimitives () protected
  {
    glGetError();
    const GLubyte * s = glewGetErrorString(glGetError());
    m_flat_shader = Shader(__PrimitivesVertexShader, __SolidFragmentShader);
    if (!m_flat_shader.init())
      return;
    GLfloat box[4][4] = {
      { -0.5f, 0.5f, 0, 1 },
      { 0.5f, 0.5f, 1, 1 },
      { -0.5f, -0.5f, 0, 0 },
      { 0.5f, -0.5f, 1, 0 }
    };
    GLfloat box_outline[4][4] = {
      { -0.5f, 0.5f, 0, 0 },
      { 0.5f, 0.5f, 1, 0 },
      { 0.5f, -0.5f, 1, 1 },
      { -0.5f, -0.5f, 0, 1 }
    };
    GLfloat line[2][4] =
    {
      {0,0,0,1},
      {1,1,1,1}
    };
    float sector_vertices[2 * CURVE_SUBDIVS][4];
    float sector_outline_vertices[2 * CURVE_SUBDIVS][4];
    float r1 = 0.0f, r2 = 1.0f;
    for (int i = 0; i < CURVE_SUBDIVS; i++)
    {
      float s = i / (float)CURVE_SUBDIVS;
      sector_vertices[i*2+0][0] = r1*sin(3.1415936f*s);
      sector_vertices[i*2+0][1] = r1*cos(3.1415936f*s);
      sector_vertices[i*2+0][2] = s;
      sector_vertices[i*2+0][3] = 0.0f;
      sector_vertices[i * 2 + 1][0] = r2 * sin(3.1415936f*s);
      sector_vertices[i * 2 + 1][1] = r2 * cos(3.1415936f*s);
      sector_vertices[i * 2 + 1][2] = s;
      sector_vertices[i * 2 + 1][3] = 1.0f;
    }
    for (int i = 0; i < CURVE_SUBDIVS; i++)
    {
      float s = i / (float)CURVE_SUBDIVS;
      sector_vertices[i][0] = r1 * sin(3.1415936f*s);
      sector_vertices[i][1] = r1 * cos(3.1415936f*s);
      sector_vertices[i][2] = s;
      sector_vertices[i][3] = 0.0f;
      sector_vertices[2 * CURVE_SUBDIVS - i - 1][0] = r2 * sin(3.1415936f*s);
      sector_vertices[2 * CURVE_SUBDIVS - i - 1][1] = r2 * cos(3.1415936f*s);
      sector_vertices[2 * CURVE_SUBDIVS - i - 1][2] = s;
      sector_vertices[2 * CURVE_SUBDIVS - i - 1][3] = 1.0f;
    }
    sggGenVertexArrays(1, &m_sector_vao);
    sggBindVertexArray(m_sector_vao);
    glGenBuffers(1, &m_sector_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, m_sector_vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof sector_vertices, sector_vertices, GL_DYNAMIC_DRAW);
    sggGenVertexArrays(1, &m_sector_outline_vao);
    sggBindVertexArray(m_sector_outline_vao);
    glGenBuffers(1, &m_sector_outline_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, m_sector_outline_vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof sector_outline_vertices, sector_outline_vertices, GL_DYNAMIC_DRAW);
    sggGenVertexArrays(1, &m_line_vao);
    sggBindVertexArray(m_line_vao);
    glGenBuffers(1, &m_line_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, m_line_vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof line, line, GL_DYNAMIC_DRAW);
    sggGenVertexArrays(1, &m_rect_vao);
    sggBindVertexArray(m_rect_vao);
    glGenBuffers(1, &m_rect_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, m_rect_vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof box, box, GL_STATIC_DRAW);
    sggGenVertexArrays(1, &m_rect_outline_vao);
    sggBindVertexArray(m_rect_outline_vao);
    glGenBuffers(1, &m_rect_outline_vbo);
    glBindBuffer(GL_ARRAY_BUFFER, m_rect_outline_vbo);
    glBufferData(GL_ARRAY_BUFFER, sizeof box_outline, box_outline, GL_STATIC_DRAW);
    unsigned int attrib_flat_position = m_flat_shader.getAttributeLocation("coord");
    glEnableVertexAttribArray(attrib_flat_position);
    glVertexAttribPointer(attrib_flat_position, 4, GL_FLOAT, GL_FALSE, 0, 0);
  }
References __PrimitivesVertexShader, __SolidFragmentShader, CURVE_SUBDIVS, Shader::getAttributeLocation(), Shader::init(), m_flat_shader, m_line_vao, m_line_vbo, m_rect_outline_vao, m_rect_outline_vbo, m_rect_vao, m_rect_vbo, m_sector_outline_vao, m_sector_outline_vbo, m_sector_vao, m_sector_vbo, sggBindVertexArray, and sggGenVertexArrays.
Referenced by init().
isMouseDragging()
bool graphics::GLBackend::isMouseDragging ()
  {
    return m_mouse_dragging;
  }
References m_mouse_dragging.
Referenced by graphics::getMouseState().
makeCurrent()
void graphics::GLBackend::makeCurrent ()
  {
    SDL_GL_MakeCurrent(m_window, m_context);
  }
References m_context, and m_window.
playMusic()
void graphics::GLBackend::playMusic (std::string soundfile, float volume, bool looping = true, int fade_time = 0)
  {
    m_audio->playMusic(soundfile, volume, looping, fade_time);
  }
References m_audio, and AudioManager::playMusic().
Referenced by graphics::playMusic().
playSound()
void graphics::GLBackend::playSound (std::string soundfile, float volume, bool looping = false)
  {
    m_audio->playSound(soundfile, volume, looping);
  }
References m_audio, and AudioManager::playSound().
Referenced by graphics::playSound().
preloadBitmaps()
std::vector< std::string > graphics::GLBackend::preloadBitmaps (std::string dir)
  {
    std::vector<std::string> names;
    Brush brush;
    fs::directory_iterator dir_iter;
    for (auto& entry : fs::directory_iterator(dir))
    {
      std::string filename = entry.path().string();
      // std::cout << filename ;
      // TODO: for now, using MSVC17-compliant code, where
      // filesystem classes are not fully implemented.
      std::string extension = filename.substr(filename.length() - 4, 4);
      std::transform(extension.begin(), extension.end(), extension.begin(),
        [](unsigned char c) { return std::tolower(c); });
      if (extension.compare(".png"))
      {
        continue;
      }
      if (textures.getTexture(filename))
      {
        names.push_back(filename);
      }
    }
    return names;
  }
References graphics::TextureManager::getTexture(), and textures.
Referenced by graphics::preloadBitmaps().
processEvent()
bool graphics::GLBackend::processEvent (SDL_Event event) protected
  {
    if (m_quit)
      return false;
    if (event.type == SDL_MOUSEMOTION)
    {
      m_prev_mouse_pos = m_mouse_pos;
      m_mouse_pos.x = event.motion.x;
      m_mouse_pos.y = event.motion.y;
      m_mouse_dragging = (m_button_state[0] || m_button_state[1] || m_button_state[2]);
    }
    else if (event.type == SDL_MOUSEBUTTONDOWN || event.type == SDL_MOUSEBUTTONUP)
    {
      bool new_state = (event.type == SDL_MOUSEBUTTONDOWN);
      switch (event.button.button)
      {
      case SDL_BUTTON_LEFT: m_button_state[0] = new_state;
      case SDL_BUTTON_MIDDLE: m_button_state[1] = new_state;
      case SDL_BUTTON_RIGHT: m_button_state[2] = new_state;
      }
    }
    else if (event.type == SDL_KEYDOWN)
    {
      switch (event.key.keysym.sym)
      {
      case SDLK_ESCAPE:
        return false;
      default:
        break;
      }
    }
    else if (event.type == SDL_WINDOWEVENT)
    {
      if (event.window.windowID == m_windowID)
      {
        if (event.window.event == SDL_WINDOWEVENT_RESIZED || event.window.event == SDL_WINDOWEVENT_SIZE_CHANGED
          || event.window.event == SDL_WINDOWEVENT_MAXIMIZED)
        {
          if (event.window.data1 != 0 && event.window.data2 != 0)
            resize(event.window.data1, event.window.data2);
        }
      }
    }
    return true;
  }
References m_button_state, m_mouse_dragging, m_mouse_pos, m_prev_mouse_pos, m_quit, m_windowID, and resize().
Referenced by processMessages().
processMessages()
bool graphics::GLBackend::processMessages ()
  {
    SDL_Event event;
    bool loop = true;
    while (SDL_PollEvent(&event) && loop)
    {
      if (event.type == SDL_WINDOWEVENT_CLOSE || event.type == SDL_QUIT)
      {
        return false;
      }
      else
      {
        loop = processEvent(event);
      }
    }
    update();
    if (m_idle_callback != nullptr)
      m_idle_callback(getDeltaTime());
    draw();
    advanceTime();
    SDL_Delay(5);
    return loop;
  }
References advanceTime(), draw(), getDeltaTime(), m_idle_callback, processEvent(), and update().
Referenced by graphics::startMessageLoop().
resetPose()
void graphics::GLBackend::resetPose ()
  {
    m_transformation = glm::mat4(1.0f);
    m_scale = glm::vec3(1.0f);
    m_orientation = 0.0f;
  }
References m_orientation, m_scale, and m_transformation.
Referenced by draw(), and graphics::resetPose().
resize()
void graphics::GLBackend::resize (int w, int h) virtual
  {
    m_width = w;
    m_height = h;
    if (m_resize_callback != nullptr)
      m_resize_callback(w, h);
    if (m_requested_canvas.z == 0 || m_requested_canvas.w == 0)
    // default canvas is window-sized, in pixel units.
      m_canvas = glm::vec4(0, 0, m_width, m_height);
    else
      m_canvas = m_requested_canvas;
    float c_w = m_canvas.z;
    float c_h = m_canvas.w;
    float cr = c_w / c_h;
    float wr = m_width / (float)m_height;
    // calculate window to canvas unit conversion ratios
    if (m_canvas_mode == CANVAS_SCALE_FIT)
    {
      if (cr > wr)
      {
        m_window_to_canvas_factors.x = c_w / m_width;
        m_window_to_canvas_factors.y = 0.0f;
        m_window_to_canvas_factors.z = c_w / m_width;
        m_window_to_canvas_factors.w = c_h / 2.0f - 0.5 * m_height * c_w / m_width;
      }
      else
      {
        m_window_to_canvas_factors.z = c_h / m_height;
        m_window_to_canvas_factors.w = 0.0f;
        m_window_to_canvas_factors.x = c_h / m_height;
        m_window_to_canvas_factors.y = c_w / 2.0f - 0.5 * m_width * c_h / m_height;
      }
    }
    else
    {
      m_window_to_canvas_factors.x = c_w / m_width;
      m_window_to_canvas_factors.y = 0.0f;
      m_window_to_canvas_factors.z = c_h / m_height;
      m_window_to_canvas_factors.w = 0.0f;
    }
    computeProjection();
    glViewport(0, 0, m_width, m_height);
    //SDL_Delay(100);
    draw();
  }
References graphics::CANVAS_SCALE_FIT, computeProjection(), draw(), m_canvas, m_canvas_mode, m_height, m_requested_canvas, m_resize_callback, m_width, and m_window_to_canvas_factors.
Referenced by draw(), processEvent(), and setFullscreen().
setBackgroundColor()
void graphics::GLBackend::setBackgroundColor (float r, float g, float b)
  {
    m_back_color = glm::vec3(r, g, b);
  }
References m_back_color.
Referenced by graphics::setWindowBackground().
setCanvasMode()
void graphics::GLBackend::setCanvasMode (int m)
  {
    m_canvas_mode = m;
    if (m == CANVAS_SCALE_WINDOW)
      m_requested_canvas = glm::vec4(0.0f);
  }
References graphics::CANVAS_SCALE_WINDOW, m_canvas_mode, and m_requested_canvas.
Referenced by graphics::setCanvasScaleMode().
setCanvasSize()
void graphics::GLBackend::setCanvasSize (float w, float h)
  {
    m_requested_canvas.z = w;
    m_requested_canvas.w = h;
  }
References m_requested_canvas.
Referenced by graphics::setCanvasSize().
setDrawCallback()
void graphics::GLBackend::setDrawCallback (std::function< void()> drf)
  {
    m_draw_callback = drf;
  }
References m_draw_callback.
Referenced by graphics::setDrawFunction().
setFont()
bool graphics::GLBackend::setFont (std::string fontname)
  {
    return m_fontlib.setCurrentFont(fontname);
  }
References m_fontlib, and FontLib::setCurrentFont().
Referenced by graphics::setFont().
setFullscreen()
void graphics::GLBackend::setFullscreen (bool fs)
  {
    if (fs)
    {
      SDL_SetWindowFullscreen(m_window, SDL_WINDOW_FULLSCREEN_DESKTOP);
    }
    else
    {
      SDL_SetWindowFullscreen(m_window, 0);
    }
    SDL_GetWindowSize(m_window, &m_width, &m_height);
    resize(m_width, m_height);
  }
References m_height, m_width, m_window, and resize().
Referenced by graphics::setFullScreen().
setIdleCallback()
void graphics::GLBackend::setIdleCallback (std::function< void(float ms)> idf)
  {
    m_idle_callback = idf;
  }
References m_idle_callback.
Referenced by graphics::setUpdateFunction().
setOrientation()
void graphics::GLBackend::setOrientation (float degrees)
  {
    m_orientation = degrees;
    computeTransformation();
  }
References computeTransformation(), and m_orientation.
Referenced by graphics::setOrientation().
setResizeCallback()
void graphics::GLBackend::setResizeCallback (std::function< void(int w, int h)> rsf)
  {
    m_resize_callback = rsf;
  }
References m_resize_callback.
Referenced by graphics::setResizeFunction().
setScale()
void graphics::GLBackend::setScale (float sx, float sy, float sz)
  {
    m_scale = glm::vec3(sx,sy,sz);
    computeTransformation();
  }
References computeTransformation(), and m_scale.
Referenced by graphics::setScale().
setUserData()
void graphics::GLBackend::setUserData (const void * user_data)
{
    m_user_data = user_data;
  }
References m_user_data.
Referenced by graphics::setUserData().
show()
void graphics::GLBackend::show (bool s)
  {
    if (s)
      SDL_ShowWindow(m_window);
    else
      SDL_HideWindow(m_window);
  }
References m_window.
Referenced by graphics::createWindow().
stopMusic()
void graphics::GLBackend::stopMusic (int fade_time = 0)
  {
    m_audio->stopMusic(fade_time);
  }
References m_audio, and AudioManager::stopMusic().
Referenced by graphics::stopMusic().
swap()
void graphics::GLBackend::swap ()
  {
    SDL_GL_SwapWindow(m_window);
  }
References m_window.
Referenced by draw().
terminate()
void graphics::GLBackend::terminate ()
  {
    m_quit = true;
  }
References m_quit.
Referenced by graphics::stopMessageLoop().
update()
void graphics::GLBackend::update (float delta_time = 0.0f) virtual
  {
    static bool prev_mouse_state[3] = { 0,0,0 };
    m_button_pressed[0] = (m_button_state[0] && !prev_mouse_state[0]);
    m_button_pressed[1] = (m_button_state[1] && !prev_mouse_state[1]);
    m_button_pressed[2] = (m_button_state[2] && !prev_mouse_state[2]);
    m_button_released[0] = (!m_button_state[0] && prev_mouse_state[0]);
    m_button_released[1] = (!m_button_state[1] && prev_mouse_state[1]);
    m_button_released[2] = (!m_button_state[2] && prev_mouse_state[2]);
    prev_mouse_state[0] = m_button_state[0];
    prev_mouse_state[1] = m_button_state[1];
    prev_mouse_state[2] = m_button_state[2];
  }
References m_button_pressed, m_button_released, and m_button_state.
Referenced by processMessages().
WindowToCanvasX()
float graphics::GLBackend::WindowToCanvasX (float x, bool clamped = true)
  {
    float coord = m_window_to_canvas_factors.x*x + m_window_to_canvas_factors.y;
    return clamped?glm::clamp(coord, 0.0f, m_canvas.z) : coord;
  }
References m_canvas, and m_window_to_canvas_factors.
Referenced by graphics::windowToCanvasX().
WindowToCanvasY()
float graphics::GLBackend::WindowToCanvasY (float y, bool clamped = true)
  {
    float coord = m_window_to_canvas_factors.z*y + m_window_to_canvas_factors.w;
    return clamped?glm::clamp(coord, 0.0f, m_canvas.w) : coord;
  }
References m_canvas, and m_window_to_canvas_factors.
Referenced by graphics::windowToCanvasY().
Member Data Documentation
m_audio
AudioManager* graphics::GLBackend::m_audio = nullptr protected
Referenced by cleanup(), init(), playMusic(), playSound(), and stopMusic().
m_back_color
glm::vec3 graphics::GLBackend::m_back_color = { 0.0f, 0.0f, 0.0f } protected
Referenced by draw(), and setBackgroundColor().
m_button_pressed
bool graphics::GLBackend::m_button_pressed[3] = { 0, 0, 0 } protected
Referenced by getMouseButtonPressed(), and update().
m_button_released
bool graphics::GLBackend::m_button_released[3] = { 0, 0, 0 } protected
Referenced by getMouseButtonReleased(), and update().
m_button_state
bool graphics::GLBackend::m_button_state[3] = { 0, 0, 0 } protected
Referenced by getMouseButtonState(), processEvent(), and update().
m_canvas
glm::vec4 graphics::GLBackend::m_canvas protected
Referenced by computeProjection(), resize(), WindowToCanvasX(), and WindowToCanvasY().
m_canvas_mode
int graphics::GLBackend::m_canvas_mode = 0 protected
Referenced by computeProjection(), draw(), resize(), and setCanvasMode().
m_context
SDL_GLContext graphics::GLBackend::m_context protected
Referenced by cleanup(), init(), and makeCurrent().
m_delta_time
float graphics::GLBackend::m_delta_time = 0.0f protected
Referenced by advanceTime(), draw(), and getDeltaTime().
m_draw_callback
std::function<void()> graphics::GLBackend::m_draw_callback = nullptr protected
Referenced by draw(), and setDrawCallback().
m_flat_shader
Shader graphics::GLBackend::m_flat_shader protected
Referenced by draw(), drawLine(), drawRect(), drawSector(), and initPrimitives().
m_fontlib
FontLib graphics::GLBackend::m_fontlib protected
Referenced by draw(), drawText(), init(), and setFont().
m_global_time
float graphics::GLBackend::m_global_time = 0.0f protected
Referenced by advanceTime(), draw(), and getGlobalTime().
m_height
int graphics::GLBackend::m_height protected
Referenced by computeProjection(), draw(), init(), resize(), and setFullscreen().
m_idle_callback
std::function<void(float ms)> graphics::GLBackend::m_idle_callback = nullptr protected
Referenced by processMessages(), and setIdleCallback().
m_idle_timer
SDL_TimerID graphics::GLBackend::m_idle_timer protected
m_initialized
bool graphics::GLBackend::m_initialized = false protected
Referenced by init().
m_line_vao
GLuint graphics::GLBackend::m_line_vao protected
Referenced by drawLine(), and initPrimitives().
m_line_vbo
GLuint graphics::GLBackend::m_line_vbo protected
Referenced by drawLine(), and initPrimitives().
m_mouse_dragging
bool graphics::GLBackend::m_mouse_dragging = false protected
Referenced by isMouseDragging(), and processEvent().
m_mouse_pos
glm::ivec2 graphics::GLBackend::m_mouse_pos = glm::ivec2() protected
Referenced by getMousePosition(), and processEvent().
m_orientation
float graphics::GLBackend::m_orientation = 0.0f protected
Referenced by computeTransformation(), resetPose(), and setOrientation().
m_prev_mouse_pos
glm::ivec2 graphics::GLBackend::m_prev_mouse_pos = glm::ivec2() protected
Referenced by getPrevMousePosition(), and processEvent().
m_prev_time_tick
std::chrono::time_point<std::chrono::steady_clock> graphics::GLBackend::m_prev_time_tick protected
Referenced by advanceTime().
m_projection
glm::mat4 graphics::GLBackend::m_projection protected
Referenced by computeProjection(), draw(), and drawText().
m_quit
bool graphics::GLBackend::m_quit = false protected
Referenced by processEvent(), and terminate().
m_rect_outline_vao
GLuint graphics::GLBackend::m_rect_outline_vao protected
Referenced by drawRect(), and initPrimitives().
m_rect_outline_vbo
GLuint graphics::GLBackend::m_rect_outline_vbo protected
Referenced by drawRect(), and initPrimitives().
m_rect_vao
GLuint graphics::GLBackend::m_rect_vao protected
Referenced by drawRect(), and initPrimitives().
m_rect_vbo
GLuint graphics::GLBackend::m_rect_vbo protected
Referenced by drawRect(), and initPrimitives().
m_requested_canvas
glm::vec4 graphics::GLBackend::m_requested_canvas = glm::vec4(0.0f) protected
Referenced by computeProjection(), draw(), resize(), setCanvasMode(), and setCanvasSize().
m_resize_callback
std::function<void(int w, int h)> graphics::GLBackend::m_resize_callback = nullptr protected
Referenced by resize(), and setResizeCallback().
m_scale
glm::vec3 graphics::GLBackend::m_scale = glm::vec3(1.0f) protected
Referenced by computeTransformation(), resetPose(), and setScale().
m_sector_outline_vao
GLuint graphics::GLBackend::m_sector_outline_vao protected
Referenced by drawSector(), and initPrimitives().
m_sector_outline_vbo
GLuint graphics::GLBackend::m_sector_outline_vbo protected
Referenced by drawSector(), and initPrimitives().
m_sector_vao
GLuint graphics::GLBackend::m_sector_vao protected
Referenced by drawSector(), and initPrimitives().
m_sector_vbo
GLuint graphics::GLBackend::m_sector_vbo protected
Referenced by drawSector(), and initPrimitives().
m_title
std::string graphics::GLBackend::m_title protected
Referenced by init().
m_transformation
glm::mat4 graphics::GLBackend::m_transformation = glm::mat4(1.0f) protected
Referenced by computeTransformation(), drawRect(), drawSector(), drawText(), and resetPose().
m_user_data
const void* graphics::GLBackend::m_user_data = nullptr protected
Referenced by getUserData(), and setUserData().
m_width
int graphics::GLBackend::m_width protected
Referenced by computeProjection(), draw(), init(), resize(), and setFullscreen().
m_window
SDL_Window* graphics::GLBackend::m_window protected
Referenced by cleanup(), init(), makeCurrent(), setFullscreen(), show(), and swap().
m_window_to_canvas_factors
glm::vec4 graphics::GLBackend::m_window_to_canvas_factors protected
Referenced by resize(), WindowToCanvasX(), and WindowToCanvasY().
m_windowID
uint32_t graphics::GLBackend::m_windowID protected
Referenced by init(), and processEvent().
textures
TextureManager graphics::GLBackend::textures protected
Referenced by drawRect(), drawSector(), and preloadBitmaps().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/include/sgg/sgg/GLbackend.h
/Users/runner/work/chess/chess/include/sgg/sgg/GLbackend.cpp