Chess: Soldier Class Reference
Soldier Class Reference
#include <Soldier.h>
Public Member Functions
Soldier (PawnColor color)
std::vector< std::pair< int, int > > getAdvanceableSquares () override
std::vector< std::pair< int, int > > getHoldingSquares () override
void promote () override
void update (float ms) override
void initiatePromotion ()
void setPromotion (std::shared_ptr< Pawn > pawn)
Public Member Functions inherited from Pawn
Pawn (PawnColor color)
void setSquare (const std::shared_ptr< Square > &square)
void capture (const std::shared_ptr< Pawn > &pawn)
std::weak_ptr< Square > getSquare () const
PawnColor getColor () const
void setTexture (std::string texture)
const std::string & getTexture () const
std::weak_ptr< Rectangle > getDrawingArea () const
void draw () override
void update (float ms) override
void move (float ms) override
void moveTo (const std::shared_ptr< Square > &squarePtr, const std::shared_ptr< Pawn > &self)
virtual std::vector< std::pair< int, int > > getAdvanceableSquares ()=0
virtual std::vector< std::pair< int, int > > getHoldingSquares ()=0
virtual std::vector< std::pair< int, int > > getAdvanceableSquares (const std::vector< pair > &steps, unsigned short int maxSteps, bool holding) const
std::vector< std::pair< int, int > > correctDirection (std::vector< std::pair< int, int > > steps) const
virtual std::weak_ptr< Pawn > getBlockedPawn ()
std::weak_ptr< Pawn > getBlockingPawn ()
bool isBlocked () const
void block ()
void unblock ()
void blockedBy (const std::shared_ptr< Pawn > &blocking)
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Public Member Functions inherited from Movable
Movable ()=default
virtual void move (float ms)=0
virtual ~Movable ()=default
Public Member Functions inherited from Promotable
Promotable ()=default
virtual void promote ()=0
virtual ~Promotable ()=default
Private Attributes
std::shared_ptr< Pawn > selectedPawn {nullptr}
Constructor & Destructor Documentation
Soldier()
Soldier::Soldier (PawnColor color) explicit
                                : Pawn(color) {
  Pawn::setTexture("soldier");
}
References Pawn::setTexture().
Member Function Documentation
getAdvanceableSquares()
std::vector< std::pair< int, int > > Soldier::getAdvanceableSquares () override virtual
Implements Pawn.
{
  std::vector<std::pair<int, int>> steps{std::vector<std::pair<int, int>>()};
  auto checkboard{static_cast<App *>(graphics::getUserData())->getGame().lock()->getCheckboard()};
  steps.push_back(std::make_pair<int, int>(1, 0));
  steps.push_back(std::make_pair<int, int>(1, 1));
  steps.push_back(std::make_pair<int, int>(1, -1));
  if (const int nextRowWhite{this->getSquare().lock()->getRow() + 1}; nextRowWhite <= 7) {
    const bool startingPositionWhite{this->getSquare().lock()->getRow() == 1};
    const bool pawnAheadWhite{checkboard->getSquareInfo(std::make_pair(nextRowWhite, this->getSquare().lock()->getColumn())).first};
    if (startingPositionWhite && Pawn::getColor() == PawnColor::WHITE && !pawnAheadWhite) {
      steps.push_back(std::make_pair<int, int>(2, 0));
    }
  }
  if (const int nextRowBlack{this->getSquare().lock()->getRow() - 1}; nextRowBlack >= 0) {
    const bool startingPositionBlack{this->getSquare().lock()->getRow() == 6};
    const bool pawnAheadBlack{checkboard->getSquareInfo(std::make_pair(nextRowBlack, this->getSquare().lock()->getColumn())).first};
    if (startingPositionBlack && Pawn::getColor() == PawnColor::BLACK && !pawnAheadBlack) {
      steps.push_back(std::make_pair<int, int>(2, 0));
    }
  }
  constexpr unsigned short int maxSteps{1};
  auto advanceableSquares{Pawn::getAdvanceableSquares(steps, maxSteps, false)};
  std::erase_if(advanceableSquares, [&checkboard, this](const auto &pair) {
    if (pair.second != this->getSquare().lock()->getColumn()) {
      const auto &[hasPawn, pawnColor]{checkboard->getSquareInfo(pair)};
      return !hasPawn;
    }
    if (pair.second == this->getSquare().lock()->getColumn()) {
      const auto &[hasPawn, pawnColor]{checkboard->getSquareInfo(pair)};
      return hasPawn;
    }
    return false;
  });
  return advanceableSquares;
}
References BLACK, Pawn::getAdvanceableSquares(), Pawn::getColor(), Pawn::getSquare(), and WHITE.
getHoldingSquares()
std::vector< std::pair< int, int > > Soldier::getHoldingSquares () override virtual
Implements Pawn.
{
  std::vector<std::pair<int, int>> steps { std::vector<std::pair<int, int>>() };
  steps.push_back(std::make_pair<int, int>(1, 1));
  steps.push_back(std::make_pair<int, int>(1, -1));
  constexpr unsigned short int maxSteps { 1 };
  auto advanceableSquares { Pawn::getAdvanceableSquares(steps, maxSteps, true) };
  std::erase_if(advanceableSquares, [this](const auto& pair) {
    if (pair.second == this->getSquare().lock()->getColumn()) {
      auto checkboard{static_cast<App *>(graphics::getUserData())->getGame().lock()->getCheckboard()};
      const auto &[hasPawn, pawnColor]{checkboard->getSquareInfo(pair)};
      return hasPawn;
    }
    return false;
  });
  return advanceableSquares;
}
References Pawn::getAdvanceableSquares().
initiatePromotion()
void Soldier::initiatePromotion ()
{
  const auto playingScreen{std::static_pointer_cast<PlayingScreen>(static_cast<App *>(graphics::getUserData())->getScreen())};
  playingScreen->getGame()->getCheckboard()->setPawnMoving(true);
  playingScreen->setPromotion(std::dynamic_pointer_cast<Soldier>(this->shared_from_this()));
}
Referenced by update().
promote()
void Soldier::promote () override virtual
Implements Promotable.
                      {
  Pawn::getSquare().lock()->unregisterPawn();
  Pawn::getSquare().lock()->registerPawn(this->selectedPawn);
}
References Pawn::getSquare(), and selectedPawn.
setPromotion()
void Soldier::setPromotion (std::shared_ptr< Pawn > pawn)
{
  this->selectedPawn = {pawn};
}
References selectedPawn.
update()
void Soldier::update (float ms) override virtual
Reimplemented from Pawn.
{
  Pawn::update(ms);
  if (Pawn::getSquare().lock()->getRow() == 7 && Pawn::getColor() == PawnColor::WHITE) {
    this->initiatePromotion();
  }
  if (Pawn::getSquare().lock()->getRow() == 0 && Pawn::getColor() == PawnColor::BLACK) {
    this->initiatePromotion();
  }
}
References BLACK, Pawn::getColor(), Pawn::getSquare(), initiatePromotion(), Pawn::update(), and WHITE.
Member Data Documentation
selectedPawn
std::shared_ptr<Pawn> Soldier::selectedPawn {nullptr} private
Referenced by promote(), and setPromotion().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/src/game/game/Soldier.h
/Users/runner/work/chess/chess/src/game/src/Soldier.cpp