Chess: Rectangle Class Reference
Rectangle Class Reference
#include <Rectangle.h>
Public Member Functions
Rectangle ()
Rectangle (Point leftBottom, float height, float width)
Rectangle (Point leftBottom, float height, float width, const graphics::Brush &brush, const Brush &type)
const graphics::Brush & getBrush () const
Brush getBrushType () const
void setBrush (Brush type, graphics::Brush brush)
void setMarkBrush (Brush brush)
void swapBrushes ()
const Point & getLeftTop () const
const Point & getRightTop () const
const Point & getLeftBottom () const
void setLeftBottom (const Point &leftBottom)
const Point & getRightBottom () const
const Point & getCenter () const
void setCenter (const Point &center)
float getHeight () const
float getWidth () const
void setHeight (float height)
void setWidth (float width)
void draw () override
void update (float ms) override
bool clicked () const
long getId () const
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Static Public Member Functions
static void populateBrushes ()
Static Public Attributes
static std::unordered_map< Brush, graphics::Brush > colors { std::unordered_map<Brush, graphics::Brush>() }
Private Attributes
Point leftTop
Point rightTop
Point leftBottom_
Point rightBottom
Point center_
float height_ {}
float width_ {}
graphics::Brush brush_ { graphics::Brush() }
Brush brushType {}
graphics::Brush markBrush { graphics::Brush() }
Brush markBrushType {}
bool selected { false }
bool swapped { false }
const long id { std::chrono::high_resolution_clock::now().time_since_epoch().count() }
Friends
bool operator== (const Rectangle &lhs, const Rectangle &rhs)
Constructor & Destructor Documentation
Rectangle() [1/3]
Rectangle::Rectangle () default
Rectangle() [2/3]
Rectangle::Rectangle (Point leftBottom, float height, float width) explicit
                                                                : leftBottom_(leftBottom), height_(height), width_(width) {
  this->leftTop = { Point(this->leftBottom_.getX(), this->leftBottom_.getY() - height) };
  this->rightBottom = { Point(this->leftBottom_.getX() + width, this->leftBottom_.getY()) };
  this->rightTop = { Point(this->rightBottom.getX(), this->leftTop.getY()) };
  this->center_ = { Point((this->leftTop.getX() + this->rightTop.getX()) / 2, (this->leftBottom_.getY() + this->leftTop.getY()) / 2) };
  Rectangle::populateBrushes();
  this->brush_ = { Rectangle::colors.at(Brush::DARK_BROWN) };
  this->markBrush = { Rectangle::colors.at(Brush::DARK_GREEN) };
  this->brushType = { Brush::DARK_BROWN };
  this->markBrushType = { Brush::DARK_GREEN };
}
References brush_, brushType, center_, colors, DARK_BROWN, DARK_GREEN, Point::getX(), leftBottom_, leftTop, markBrush, markBrushType, populateBrushes(), rightBottom, and rightTop.
Rectangle() [3/3]
Rectangle::Rectangle (Point leftBottom, float height, float width, const graphics::Brush & brush, const Brush & type) explicit
                                                                                                               : Rectangle(leftBottom, height, width) {
  this->brush_ = { brush };
  this->brushType = { type };
}
References brush_, and brushType.
Member Function Documentation
clicked()
bool Rectangle::clicked () const
{
  graphics::MouseState mouse { graphics::MouseState() };
  graphics::getMouseState(mouse);
  const float mouseHorizontalPoint { graphics::windowToCanvasX(static_cast<float>(mouse.cur_pos_x)) };
  const float mouseVerticalPoint { graphics::windowToCanvasY(static_cast<float>(mouse.cur_pos_y)) };
  bool inVerticalSpace { false };
  bool inHorizontalSpace { false };
  if (mouseVerticalPoint >= this->leftTop.getY() && mouseVerticalPoint <= this->leftBottom_.getY()) {
    inVerticalSpace = { true };
  }
  if (mouseHorizontalPoint >= this->leftTop.getX() && mouseHorizontalPoint <= this->rightTop.getX()) {
    inHorizontalSpace = { true };
  }
  return mouse.button_left_pressed && inVerticalSpace && inHorizontalSpace;
}
References Point::getX(), Point::getY(), leftBottom_, leftTop, and rightTop.
Referenced by Square::update().
draw()
void Rectangle::draw () override virtual
Implements Drawable.
                     {
  if (const auto &game { static_cast<App*>(graphics::getUserData())->getGame() }; game != nullptr) {
    if (game->getCheckboard()->amISelected(this) || game->getCheckboard()->amIinDanger(this)) {
      this->selected = { true };
    } else {
      this->selected = { false };
    }
  } else {
    this->selected = { false };
  }
  graphics::Brush brush { this->selected ? Rectangle::colors.at(Brush::RED) : this->brush_ };
  graphics::drawRect(
      this->center_.getX(),
      this->center_.getY(),
      this->width_,
      this->height_,
      brush
  );
}
References brush_, center_, colors, Point::getX(), RED, and selected.
Referenced by Checkboard::draw(), Pawn::draw(), and Square::draw().
getBrush()
const graphics::Brush & Rectangle::getBrush () const
{
  return this->brush_;
}
References brush_.
Referenced by Pawn::move(), and Pawn::moveTo().
getBrushType()
Brush Rectangle::getBrushType () const
{
  return this->brushType;
}
References brushType.
Referenced by Pawn::move(), and Pawn::moveTo().
getCenter()
const Point & Rectangle::getCenter () const
{
  return this->center_;
}
References center_.
getHeight()
float Rectangle::getHeight () const
{
  return this->height_;
}
References height_.
Referenced by Pawn::setSquare().
getId()
long Rectangle::getId () const
{
  return this->id;
}
References id.
Referenced by Checkboard::amIinDanger(), and Checkboard::moveKing().
getLeftBottom()
const Point & Rectangle::getLeftBottom () const
{
  return this->leftBottom_;
}
References leftBottom_.
Referenced by Pawn::move(), Pawn::moveTo(), and Pawn::setSquare().
getLeftTop()
const Point & Rectangle::getLeftTop () const
{
  return this->leftTop;
}
References leftTop.
getRightBottom()
const Point & Rectangle::getRightBottom () const
{
  return this->rightBottom;
}
References rightBottom.
getRightTop()
const Point & Rectangle::getRightTop () const
{
  return this->rightTop;
}
References rightTop.
getWidth()
float Rectangle::getWidth () const
{
  return this->width_;
}
References width_.
Referenced by Pawn::setSquare().
populateBrushes()
void Rectangle::populateBrushes () static
{
  graphics::Brush lightBrown { graphics::Brush() };
  lightBrown.fill_color[0] = { 1.0f };
  lightBrown.fill_color[1] = { 0.9137f };
  lightBrown.fill_color[2] = { 0.7725f };
  lightBrown.fill_opacity = { 1.0f };
  lightBrown.outline_opacity = { 0.0f };
  lightBrown.outline_width = { 0.0f };
  graphics::Brush darkBrown { graphics::Brush() };
  darkBrown.fill_color[0] = { 0.4588f };
  darkBrown.fill_color[1] = { 0.2901f };
  darkBrown.fill_color[2] = { 0.0f };
  darkBrown.fill_opacity = { 1.0f };
  darkBrown.outline_opacity = { 0.0f };
  darkBrown.outline_width = { 0.0f };
  graphics::Brush lightGreen { graphics::Brush() };
  lightGreen.fill_color[0] = { 0.0f };
  lightGreen.fill_color[1] = { 1.0f };
  lightGreen.fill_color[2] = { 0.1725f };
  lightGreen.fill_opacity = { 0.5f };
  lightGreen.outline_opacity = { 0.0f };
  lightGreen.outline_width = { 0.0f };
  graphics::Brush darkGreen { graphics::Brush() };
  darkGreen.fill_color[0] = { 0.2392f };
  darkGreen.fill_color[1] = { 0.4f };
  darkGreen.fill_color[2] = { 0.0f };
  darkGreen.fill_opacity = { 0.5f };
  darkGreen.outline_opacity = { 0.0f };
  darkGreen.outline_width = { 0.0f };
  graphics::Brush red { graphics::Brush() };
  red.fill_color[0] = { 0.5803f };
  red.fill_color[1] = { 0.0f };
  red.fill_color[2] = { 0.0f };
  red.fill_opacity = { 0.5f };
  red.outline_opacity = { 0.0f };
  red.outline_width = { 0.0f };
  graphics::Brush texture { graphics::Brush() };
  texture.fill_color[0] = { 1.0f };
  texture.fill_color[1] = { 1.0f };
  texture.fill_color[2] = { 1.0f };
  texture.fill_opacity = { 1.0f };
  texture.outline_opacity = { 0.0f };
  texture.outline_width = { 0.0f };
  graphics::Brush checkboard { graphics::Brush() };
  checkboard.fill_color[0] = { 1.0f };
  checkboard.fill_color[1] = { 1.0f };
  checkboard.fill_color[2] = { 1.0f };
  checkboard.fill_opacity = { 1.0f };
  checkboard.outline_width = { 10 };
  checkboard.outline_opacity = { 1.0f };
  checkboard.outline_color[0] = { 0.4588f };
  checkboard.outline_color[1] = { 0.2901f };
  checkboard.outline_color[2] = { 0.0f };
  Rectangle::colors.try_emplace(Brush::LIGHT_BROWN, lightBrown);
  Rectangle::colors.try_emplace(Brush::DARK_BROWN, darkBrown);
  Rectangle::colors.try_emplace(Brush::LIGHT_GREEN, lightGreen);
  Rectangle::colors.try_emplace(Brush::DARK_GREEN, darkGreen);
  Rectangle::colors.try_emplace(Brush::RED, red);
  Rectangle::colors.try_emplace(Brush::TEXTURE, texture);
  Rectangle::colors.try_emplace(Brush::CHECKBOARD, checkboard);
}
References CHECKBOARD, colors, DARK_BROWN, DARK_GREEN, LIGHT_BROWN, LIGHT_GREEN, RED, and TEXTURE.
Referenced by Rectangle(), and App::run().
setBrush()
void Rectangle::setBrush (Brush type, graphics::Brush brush)
{
  this->brushType = { type };
  this->brush_ = { std::move(brush) };
}
References brush_, and brushType.
Referenced by Square::initialize(), MenuOption::MenuOption(), Pawn::setSquare(), HUD::setTextBrush(), and Square::Square().
setCenter()
void Rectangle::setCenter (const Point & center)
{
  this->center_ = { center };
  this->leftTop = { Point((this->center_.getX() * 2) - this->width_, this->center_.getY() * 2) };
  this->rightTop = { Point(this->leftTop.getX() + this->width_, this->leftTop.getY()) };
  this->rightBottom = { Point(this->rightTop.getX(), this->rightTop.getY() - this->height_) };
  this->leftBottom_ = { Point(this->leftTop.getX(), this->rightBottom.getY()) };
}
References center_, Point::getX(), leftBottom_, leftTop, rightBottom, and rightTop.
Referenced by HUD::HUD().
setHeight()
void Rectangle::setHeight (float height)
{
  this->height_ = { height };
}
References height_.
Referenced by HUD::HUD(), Square::initialize(), MenuOption::MenuOption(), Pawn::setSquare(), and Square::Square().
setLeftBottom()
void Rectangle::setLeftBottom (const Point & leftBottom)
{
  this->leftBottom_ = { leftBottom };
  this->leftTop = { Point(this->leftBottom_.getX(), this->leftBottom_.getY() - this->height_) };
  this->rightBottom = { Point(this->leftBottom_.getX() + this->width_, this->leftBottom_.getY()) };
  this->rightTop = { Point(this->rightBottom.getX(), this->leftTop.getY()) };
  this->center_ = { Point((this->leftTop.getX() + this->rightTop.getX()) / 2, (this->leftBottom_.getY() + this->leftTop.getY()) / 2) };
}
References center_, Point::getX(), leftBottom_, leftTop, rightBottom, and rightTop.
Referenced by Square::initialize(), MenuOption::MenuOption(), Pawn::move(), Pawn::setSquare(), and Square::Square().
setMarkBrush()
void Rectangle::setMarkBrush (Brush brush)
{
  this->markBrush = { Rectangle::colors.at(brush) };
  this->markBrushType = { brush };
}
References colors, markBrush, and markBrushType.
Referenced by Square::Square().
setWidth()
void Rectangle::setWidth (float width)
{
  this->width_ = { width };
}
References width_.
Referenced by HUD::HUD(), Square::initialize(), MenuOption::MenuOption(), Pawn::setSquare(), and Square::Square().
swapBrushes()
void Rectangle::swapBrushes ()
{
  std::swap(this->brush_, this->markBrush);
  std::swap(this->brushType, this->markBrushType);
  this->swapped = { !this->swapped };
}
References brush_, brushType, markBrush, markBrushType, and swapped.
Referenced by update().
update()
void Rectangle::update (float ms) override virtual
Implements Updateable.
{
  if (const auto& game { static_cast<App*>(graphics::getUserData())->getGame() }; game != nullptr) {
    if (game->getCheckboard()->shouldMark(this)) {
      if (!this->swapped) {
        this->swapBrushes();
      }
    } else {
      if (this->swapped) {
        this->swapBrushes();
      }
    }
  }
}
References swapBrushes(), and swapped.
Referenced by Square::update().
Friends And Related Function Documentation
operator==
bool operator== (const Rectangle & lhs, const Rectangle & rhs) friend
{
  return lhs.id == rhs.id;
}
Member Data Documentation
brush_
graphics::Brush Rectangle::brush_ { graphics::Brush() } private
Referenced by draw(), getBrush(), Rectangle(), setBrush(), and swapBrushes().
brushType
Brush Rectangle::brushType {} private
Referenced by getBrushType(), Rectangle(), setBrush(), and swapBrushes().
center_
Point Rectangle::center_ private
Referenced by draw(), getCenter(), Rectangle(), setCenter(), and setLeftBottom().
colors
std::unordered_map<Brush, graphics::Brush> Rectangle::colors { std::unordered_map<Brush, graphics::Brush>() } inline static
Referenced by OpeningScreen::draw(), draw(), PlayingScreen::getSquare(), MenuOption::MenuOption(), PlayingScreen::PlayingScreen(), populateBrushes(), Rectangle(), setMarkBrush(), Pawn::setSquare(), HUD::setTextBrush(), and Square::Square().
height_
float Rectangle::height_ {} private
Referenced by getHeight(), and setHeight().
id
const long Rectangle::id { std::chrono::high_resolution_clock::now().time_since_epoch().count() } private
Referenced by getId().
leftBottom_
Point Rectangle::leftBottom_ private
Referenced by clicked(), getLeftBottom(), Rectangle(), setCenter(), and setLeftBottom().
leftTop
Point Rectangle::leftTop private
Referenced by clicked(), getLeftTop(), Rectangle(), setCenter(), and setLeftBottom().
markBrush
graphics::Brush Rectangle::markBrush { graphics::Brush() } private
Referenced by Rectangle(), setMarkBrush(), and swapBrushes().
markBrushType
Brush Rectangle::markBrushType {} private
Referenced by Rectangle(), setMarkBrush(), and swapBrushes().
rightBottom
Point Rectangle::rightBottom private
Referenced by getRightBottom(), Rectangle(), setCenter(), and setLeftBottom().
rightTop
Point Rectangle::rightTop private
Referenced by clicked(), getRightTop(), Rectangle(), setCenter(), and setLeftBottom().
selected
bool Rectangle::selected { false } private
Referenced by draw().
swapped
bool Rectangle::swapped { false } private
Referenced by swapBrushes(), and update().
width_
float Rectangle::width_ {} private
Referenced by getWidth(), and setWidth().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/include/graphics/Rectangle.h
/Users/runner/work/chess/chess/src/graphics/Rectangle.cpp