Chess: Shader Class Reference
Shader Class Reference
#include <shader.h>
Public Member Functions
operator bool () const
Shader (const char *vertex=nullptr, const char *fragment=nullptr)
Uniform & operator[] (const char *name)
bool use (bool use=true)
std::string loadShaderText (char *file)
bool init ()
void setFragmentLocation (char *name, unsigned int location)
unsigned int getAttributeLocation (const char *attrib)
~Shader ()
Public Attributes
unsigned int program
Protected Member Functions
void printLog (unsigned int obj)
Private Attributes
std::map< const char *, Uniform > uniforms
bool ready = false
unsigned int vshader
unsigned int fshader
Constructor & Destructor Documentation
Shader()
Shader::Shader (const char * vertex = nullptr, const char * fragment = nullptr)
{
  if (!vertex || !fragment)
    return;
  vshader = glCreateShader(GL_VERTEX_SHADER);
  glShaderSource(vshader, 1, &vertex, NULL);
  fshader = glCreateShader(GL_FRAGMENT_SHADER);
  glShaderSource(fshader, 1, &fragment, NULL);
  GLint status;
  glCompileShader(vshader);
  glGetShaderiv(vshader, GL_COMPILE_STATUS, &status);
  if (!status)
  {
    printLog(vshader);
    return;
  }
  glCompileShader(fshader);
  glGetShaderiv(fshader, GL_COMPILE_STATUS, &status);
  if (!status)
  {
    printLog(fshader);
    return;
  }
  program = glCreateProgram();
  glAttachShader(program, vshader);
  glAttachShader(program, fshader);
  glLinkProgram(program);
  assert(glGetError() == GL_NO_ERROR);
//  GLint status;
  glGetProgramiv(program, GL_LINK_STATUS, &status);
  if (!status)
  {
    printLog(program);
    return;
  }
  glValidateProgram(program);
  glGetProgramiv(program, GL_VALIDATE_STATUS, &status);
  if (!status)
  {
    printLog(program);
    return;
  }
}
References fshader, printLog(), program, and vshader.
~Shader()
Shader::~Shader ()
{
  glDetachShader(program, vshader);
  glDeleteShader(vshader);
  glDetachShader(program, fshader);
  glDeleteShader(fshader);
}
References fshader, program, and vshader.
Member Function Documentation
getAttributeLocation()
unsigned int Shader::getAttributeLocation (const char * attrib)
{
  return glGetAttribLocation(program, attrib);
}
References program.
Referenced by graphics::GLBackend::drawLine(), graphics::GLBackend::drawRect(), graphics::GLBackend::drawSector(), FontLib::init(), and graphics::GLBackend::initPrimitives().
init()
bool Shader::init ()
{
  ready = true;
  return true;
}
References ready.
Referenced by FontLib::init(), and graphics::GLBackend::initPrimitives().
loadShaderText()
std::string Shader::loadShaderText (char * file)
{
  return std::string();
}
operator bool()
Shader::operator bool () const inline explicit
{ return ready; }
References ready.
operator[]()
Uniform & Shader::operator[] (const char * name)
{
  auto iter = uniforms.find(name);
  if (iter == uniforms.end())
  {
    Uniform uni = glGetUniformLocation(program, name);
    uniforms[name] = uni;
    return uniforms[name];
  }
  else
  {
    return iter->second;
  }
}
References program, and uniforms.
printLog()
void Shader::printLog (unsigned int obj) protected
{
  GLint log_length = 0;
  if (glIsShader(object))
    glGetShaderiv(object, GL_INFO_LOG_LENGTH, &log_length);
  else if (glIsProgram(object))
    glGetProgramiv(object, GL_INFO_LOG_LENGTH, &log_length);
  else
  {
    printf("printlog: Not a shader or a program\n");
    return;
  }
  if (log_length == 0)
    return;
  char* log = new char[log_length];
  if (glIsShader(object))
    glGetShaderInfoLog(object, log_length, NULL, log);
  else if (glIsProgram(object))
    glGetProgramInfoLog(object, log_length, NULL, log);
  printf("%s", log);
  delete[] log;
}
Referenced by Shader().
setFragmentLocation()
void Shader::setFragmentLocation (char * name, unsigned int location)
{
  glBindFragDataLocation(program, location, name);
}
References program.
use()
bool Shader::use (bool use = true)
{
  if (!ready)
    return false;
  if (use)
    glUseProgram(program);
  else
    glUseProgram(0);
  return true;
}
References program, ready, and use().
Referenced by FontLib::commitText(), graphics::GLBackend::draw(), graphics::GLBackend::drawRect(), graphics::GLBackend::drawSector(), FontLib::drawText(), and use().
Member Data Documentation
fshader
unsigned int Shader::fshader private
Referenced by Shader(), and ~Shader().
program
unsigned int Shader::program
Referenced by getAttributeLocation(), operator[](), setFragmentLocation(), Shader(), use(), and ~Shader().
ready
bool Shader::ready = false private
Referenced by init(), operator bool(), and use().
uniforms
std::map<const char *, Uniform> Shader::uniforms private
Referenced by operator[]().
vshader
unsigned int Shader::vshader private
Referenced by Shader(), and ~Shader().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/include/sgg/sgg/shader.h
/Users/runner/work/chess/chess/include/sgg/sgg/shader.cpp