Chess: Sound Class Reference
Sound Class Reference
#include <Sound.h>
Public Member Functions
void play () const
void setSound (const std::string &path)
Protected Member Functions
Sound ()
Private Attributes
std::string soundPath {}
Static Private Attributes
static constexpr bool looping {false}
static constexpr float volume {1.0f}
Constructor & Destructor Documentation
Sound()
Sound::Sound () protected default
Member Function Documentation
play()
void Sound::play () const
                       {
  graphics::playSound(this->soundPath, Sound::volume, Sound::looping);
}
References looping, soundPath, and volume.
Referenced by Pawn::capture(), Game::end(), Pawn::moveTo(), Game::playCheckSound(), MenuOption::playSound(), and Pawn::update().
setSound()
void Sound::setSound (const std::string & path)
{
  this->soundPath = {path};
}
References soundPath.
Referenced by CaptureSound::CaptureSound(), CheckSound::CheckSound(), ClickSound::ClickSound(), EndgameSound::EndgameSound(), and MoveSound::MoveSound().
Member Data Documentation
looping
constexpr bool Sound::looping {false} static constexpr private
Referenced by play().
soundPath
std::string Sound::soundPath {} private
Referenced by play(), and setSound().
volume
constexpr float Sound::volume {1.0f} static constexpr private
Referenced by play().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/src/sounds/sounds/Sound.h
/Users/runner/work/chess/chess/src/sounds/src/Sound.cpp