Chess: InGameMenu Class Reference
InGameMenu Class Reference
#include <InGameMenu.h>
Public Member Functions
InGameMenu ()
void draw () override
void update (float ms) override
void pressButton (const ButtonType &type) const override
Public Member Functions inherited from Menu
Menu ()
void draw () override=0
void update (float ms) override=0
void addOption (const MenuOption &option, ButtonType buttonType)
const MenuOption & getMenuOption (ButtonType buttonType)
const std::unordered_map< ButtonType, MenuOption > & getMenuOptions () const
virtual void pressButton (const ButtonType &type) const =0
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Constructor & Destructor Documentation
InGameMenu()
InGameMenu::InGameMenu ()
                       {
  const std::string message{"Quit game"};
  const float verticalPoint{600.0f};
  const std::size_t size{100};
  const float horizontalPoint{2400.0f};
  const auto coordinates{std::make_pair(horizontalPoint, verticalPoint)};
  HUD menuHud{HUD(message, coordinates, size)};
  menuHud.setTextBrush(Brush::LIGHT_BROWN);
  Menu::addOption(MenuOption(menuHud), ButtonType::QUIT);
}
References Menu::addOption(), LIGHT_BROWN, QUIT, and HUD::setTextBrush().
Member Function Documentation
draw()
void InGameMenu::draw () override virtual
Implements Menu.
                      {
  for (const auto &[type, option]: Menu::getMenuOptions()) {
    option.getMessage().draw();
    option.getButton().draw();
  }
}
References Menu::getMenuOptions().
pressButton()
void InGameMenu::pressButton (const ButtonType & type) const override virtual
Implements Menu.
{
  if (type == ButtonType::QUIT) {
    App *app{static_cast<App *>(graphics::getUserData())};
    app->changeScreen(std::make_shared<OpeningScreen>());
  }
}
References App::changeScreen(), and QUIT.
Referenced by update().
update()
void InGameMenu::update (float ms) override virtual
Implements Menu.
{
  std::ranges::for_each(this->getMenuOptions().begin(), this->getMenuOptions().end(), [&ms](const auto &pair) {
    pair.second.getMessage().update(ms);
    pair.second.getButton().update(ms);
    if (pair.second.getButton().clicked()) {
      pair.second.playSound();
    }
  });
  if (Menu::getMenuOption(ButtonType::QUIT).getButton().clicked()) {
    this->pressButton(ButtonType::QUIT);
  }
}
References Menu::getMenuOption(), Menu::getMenuOptions(), pressButton(), QUIT, and update().
Referenced by update().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/src/graphics/graphics/InGameMenu.h
/Users/runner/work/chess/chess/src/graphics/src/InGameMenu.cpp