Chess: Game Class Reference
Game Class Reference
#include <Game.h>
Public Member Functions
Game ()
bool start ()
void registerPlayers (const std::pair< Player, Player > &pair)
const Player & getPlayer (PawnColor side)
std::shared_ptr< Checkboard > getCheckboard () const
void draw () override
void update (float ms) override
bool isWhiteTurn () const
void setWhiteTurn (bool white_turn)
void end (PawnColor color)
std::pair< bool, std::optional< PawnColor > > hasGameEnded () const
std::optional< PawnColor > isChecked ()
void playCheckSound () const
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Private Attributes
std::optional< std::pair< Player, Player > > players
std::shared_ptr< Checkboard > checkboard {std::make_shared<Checkboard>()}
bool whiteTurn_ {true}
bool isGameEnded {false}
std::optional< PawnColor > winner {std::make_optional<PawnColor>()}
EndgameSound checkmateSound {EndgameSound()}
CheckSound checkSound {CheckSound()}
std::optional< PawnColor > checkedColor {}
Constructor & Destructor Documentation
Game()
Game::Game () default
Member Function Documentation
draw()
void Game::draw () override virtual
Implements Drawable.
                {
  this->checkboard->draw();
}
References checkboard.
end()
void Game::end (PawnColor color)
{
  this->checkmateSound.play();
  this->isGameEnded = {true};
  this->winner.emplace(color);
}
References checkmateSound, isGameEnded, Sound::play(), and winner.
getCheckboard()
std::shared_ptr< Checkboard > Game::getCheckboard () const
{
  return this->checkboard;
}
References checkboard.
getPlayer()
const Player & Game::getPlayer (PawnColor side)
{
  if (this->players->first.getSide() == side) {
    return this->players->first;
  }
  return this->players->second;
}
References players.
hasGameEnded()
std::pair< bool, std::optional< PawnColor > > Game::hasGameEnded () const
{
  return std::make_pair(this->isGameEnded, this->winner);
}
References isGameEnded, and winner.
isChecked()
std::optional< PawnColor > Game::isChecked ()
{
  const auto whiteKing{this->checkboard->getKing(PawnColor::WHITE)};
  const auto blackKing{this->checkboard->getKing(PawnColor::BLACK)};
  if ((!blackKing.expired()) && (!whiteKing.expired())) {
    if (whiteKing.lock()->isChecked()) {
      this->checkedColor = {std::make_optional(PawnColor::WHITE)};
    }
    if (blackKing.lock()->isChecked()) {
      this->checkedColor = {std::make_optional(PawnColor::BLACK)};
    }
    if (!whiteKing.lock()->isChecked() && !blackKing.lock()->isChecked()) {
      this->checkedColor.reset();
    }
  }
  return this->checkedColor;
}
References BLACK, checkboard, checkedColor, and WHITE.
isWhiteTurn()
bool Game::isWhiteTurn () const
{
  return this->whiteTurn_;
}
References whiteTurn_.
playCheckSound()
void Game::playCheckSound () const
{
  const auto whiteKing{this->checkboard->getKing(PawnColor::WHITE)};
  const auto blackKing{this->checkboard->getKing(PawnColor::BLACK)};
  if ((whiteKing.lock()->isChecked() && this->whiteTurn_) || (blackKing.lock()->isChecked() && !this->whiteTurn_)) {
    this->checkSound.play();
  }
}
References BLACK, checkboard, checkSound, Sound::play(), and WHITE.
registerPlayers()
void Game::registerPlayers (const std::pair< Player, Player > & pair)
{
  this->players = { pair };
}
References players.
setWhiteTurn()
void Game::setWhiteTurn (bool white_turn)
{
  this->whiteTurn_ = {whiteTurn};
}
References whiteTurn_.
start()
bool Game::start ()
                 {
  App* app { static_cast<App*>(graphics::getUserData()) };
  app->registerGame(this->shared_from_this());
  return true;
}
References App::registerGame().
Referenced by update().
update()
void Game::update (float ms) override virtual
Implements Updateable.
{
  this->checkboard->update(ms);
  if (const App * app{static_cast<App *>(graphics::getUserData())}; app->getGame().expired()) {
    this->start();
  }
}
References checkboard, App::getGame(), and start().
Member Data Documentation
checkboard
std::shared_ptr<Checkboard> Game::checkboard {std::make_shared<Checkboard>()} private
Referenced by draw(), getCheckboard(), isChecked(), playCheckSound(), and update().
checkedColor
std::optional<PawnColor> Game::checkedColor {} private
Referenced by isChecked().
checkmateSound
EndgameSound Game::checkmateSound {EndgameSound()} private
Referenced by end().
checkSound
CheckSound Game::checkSound {CheckSound()} private
Referenced by playCheckSound().
isGameEnded
bool Game::isGameEnded {false} private
Referenced by end(), and hasGameEnded().
players
std::optional<std::pair<Player, Player> > Game::players private
Referenced by getPlayer(), and registerPlayers().
whiteTurn_
bool Game::whiteTurn_ {true} private
Referenced by isWhiteTurn(), and setWhiteTurn().
winner
std::optional<PawnColor> Game::winner {std::make_optional<PawnColor>()} private
Referenced by end(), and hasGameEnded().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/src/game/game/Game.h
/Users/runner/work/chess/chess/src/game/src/Game.cpp