Chess: Bishop Class Reference
Bishop Class Reference
#include <Bishop.h>
Public Member Functions
Bishop (PawnColor color)
std::vector< std::pair< int, int > > getAdvanceableSquares () override
std::vector< std::pair< int, int > > getHoldingSquares () override
std::shared_ptr< Pawn > getBlockedPawn () override
Public Member Functions inherited from Pawn
Pawn (PawnColor color)
void setSquare (Square *square)
Square * getSquare () const
PawnColor getColor () const
void setTexture (std::string texture)
const std::string & getTexture () const
std::shared_ptr< Rectangle > getDrawingArea () const
void draw () override
void update (float ms) override
void move (float ms) override
void moveTo (Square *squarePtr, const std::shared_ptr< Pawn > &self)
virtual std::vector< std::pair< int, int > > getAdvanceableSquares (const std::vector< pair > &steps, unsigned short int maxSteps, bool holding) const
std::vector< std::pair< int, int > > correctDirection (std::vector< std::pair< int, int > > steps) const
std::shared_ptr< Pawn > getBlockingPawn ()
bool isBlocked () const
void block ()
void unblock ()
void blockedBy (const std::shared_ptr< Pawn > &blocking)
Public Member Functions inherited from Drawable
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual ~Updateable ()=default
Public Member Functions inherited from Movable
Movable ()=default
virtual ~Movable ()=default
Private Attributes
std::vector< std::pair< int, int > > steps { std::vector<std::pair<int, int>>() }
Static Private Attributes
static constexpr unsigned short int maxSteps { 8 }
Additional Inherited Members
Static Public Member Functions inherited from Pawn
static void capture (const std::shared_ptr< Pawn > &pawn)
Constructor & Destructor Documentation
Bishop()
Bishop::Bishop (PawnColor color) explicit
                              : Pawn(color) {
  Pawn::setTexture("bishop");
  this->steps.push_back(std::make_pair<int, int>(1, 1));
  this->steps.push_back(std::make_pair<int, int>(-1, 1));
  this->steps.push_back(std::make_pair<int, int>(1, -1));
  this->steps.push_back(std::make_pair<int, int>(-1, -1));
}
References Pawn::setTexture(), and steps.
Member Function Documentation
getAdvanceableSquares()
std::vector< std::pair< int, int > > Bishop::getAdvanceableSquares () override virtual
Implements Pawn.
{
  return Pawn::getAdvanceableSquares(this->steps, Bishop::maxSteps, false);
}
References Pawn::getAdvanceableSquares(), maxSteps, and steps.
getBlockedPawn()
std::shared_ptr< Pawn > Bishop::getBlockedPawn () override virtual
Reimplemented from Pawn.
{
  const unsigned short int currentRow { this->getSquare()->getRow() };
  const unsigned short int currentColumn { this->getSquare()->getColumn() };
  unsigned short int nextRow { currentRow };
  unsigned short int nextColumn { currentColumn };
  for (const auto& [rowStep, columnStep] : Pawn::correctDirection(this->steps)) {
    bool shouldTerminate { false };
    bool foundPawn { false };
    std::shared_ptr<Pawn> pawn { nullptr };
    unsigned short int numberOfSteps { 0 };
    while (!shouldTerminate) {
      nextRow += rowStep;
      nextColumn += columnStep;
      if ((nextRow >= Checkboard::sideSize || nextColumn >= Checkboard::sideSize) || numberOfSteps == Bishop::maxSteps) {
        shouldTerminate = { true };
        continue;
      }
      ++numberOfSteps;
      auto checkboard { static_cast<App *>(graphics::getUserData())->getGame()->getCheckboard() };
      std::pair<int, int> squareCoordinates { std::make_pair<int, int>(nextRow, nextColumn) };
      auto [hasPawn, pawnColor] { checkboard->getSquareInfo(squareCoordinates) };
      if (hasPawn && pawnColor != Pawn::getColor() && foundPawn && checkboard->isKing(pawn->getColor(), squareCoordinates)) {
        return pawn;
      }
      if (hasPawn && pawnColor != Pawn::getColor() && foundPawn) {
        shouldTerminate = { true };
      }
      if (hasPawn && pawnColor != Pawn::getColor()) {
        pawn = { checkboard->getSquare(squareCoordinates)->getPawn() };
        foundPawn = { true };
      }
    }
    nextRow = { currentRow };
    nextColumn = { currentColumn };
  }
  return nullptr;
}
References Pawn::correctDirection(), Pawn::getColor(), Square::getColumn(), Square::getRow(), Pawn::getSquare(), maxSteps, Checkboard::sideSize, and steps.
getHoldingSquares()
std::vector< std::pair< int, int > > Bishop::getHoldingSquares () override virtual
Implements Pawn.
{
  return Pawn::getAdvanceableSquares(this->steps, Bishop::maxSteps, true);
}
References Pawn::getAdvanceableSquares(), maxSteps, and steps.
Member Data Documentation
maxSteps
constexpr unsigned short int Bishop::maxSteps { 8 } static constexpr private
Referenced by getAdvanceableSquares(), getBlockedPawn(), and getHoldingSquares().
steps
std::vector<std::pair<int, int> > Bishop::steps { std::vector<std::pair<int, int>>() } private
Referenced by Bishop(), getAdvanceableSquares(), getBlockedPawn(), and getHoldingSquares().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/include/game/Bishop.h
/Users/runner/work/chess/chess/src/game/Bishop.cpp