Chess: Pawn Class Reference
Pawn Class Reference abstract
#include <Pawn.h>
Public Member Functions
Pawn (PawnColor color)
void setSquare (const std::shared_ptr< Square > &square)
void capture (const std::shared_ptr< Pawn > &pawn)
std::weak_ptr< Square > getSquare () const
PawnColor getColor () const
void setTexture (std::string texture)
const std::string & getTexture () const
std::weak_ptr< Rectangle > getDrawingArea () const
void draw () override
void update (float ms) override
void move (float ms) override
void moveTo (const std::shared_ptr< Square > &squarePtr, const std::shared_ptr< Pawn > &self)
virtual std::vector< std::pair< int, int > > getAdvanceableSquares ()=0
virtual std::vector< std::pair< int, int > > getHoldingSquares ()=0
virtual std::vector< std::pair< int, int > > getAdvanceableSquares (const std::vector< pair > &steps, unsigned short int maxSteps, bool holding) const
std::vector< std::pair< int, int > > correctDirection (std::vector< std::pair< int, int > > steps) const
virtual std::weak_ptr< Pawn > getBlockedPawn ()
std::weak_ptr< Pawn > getBlockingPawn ()
bool isBlocked () const
void block ()
void unblock ()
void blockedBy (const std::shared_ptr< Pawn > &blocking)
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Public Member Functions inherited from Movable
Movable ()=default
virtual void move (float ms)=0
virtual ~Movable ()=default
Private Types
using pair = std::pair< int, int >
Private Attributes
PawnColor color
std::weak_ptr< Square > square_ {std::weak_ptr<Square>()}
std::weak_ptr< Square > movingSquare {std::weak_ptr<Square>()}
Rectangle drawingArea {Rectangle()}
std::string texture_ {}
const std::string png {".png"}
bool shouldMove {false}
std::pair< float, float > moveSteps {}
std::weak_ptr< Square > destination_ {std::weak_ptr<Square>()}
std::shared_ptr< Pawn > self_ {nullptr}
bool blocked {false}
std::weak_ptr< Pawn > blockingPawn {std::weak_ptr<Pawn>()}
ClickSound clickSound {ClickSound()}
MoveSound moveSound {MoveSound()}
CaptureSound captureSound {CaptureSound()}
Member Typedef Documentation
pair
using Pawn::pair = std::pair<int, int> private
Constructor & Destructor Documentation
Pawn()
Pawn::Pawn (PawnColor color) explicit
: color(color) {}
Member Function Documentation
block()
void Pawn::block ()
                 {
  this->blocked = { true };
}
References blocked.
blockedBy()
void Pawn::blockedBy (const std::shared_ptr< Pawn > & blocking)
{
  this->blockingPawn = { blocking };
}
References blockingPawn.
capture()
void Pawn::capture (const std::shared_ptr< Pawn > & pawn)
{
  this->captureSound.play();
  std::shared_ptr<PlayingScreen> playingScreen{static_pointer_cast<PlayingScreen>(static_cast<App *>(graphics::getUserData())->getScreen())};
  std::shared_ptr<Square> square{playingScreen->getSquare(pawn)};
  if (square != nullptr) {
    square->registerPawn(pawn);
    pawn->getSquare().lock()->unregisterPawn();
  }
}
References captureSound, and Sound::play().
Referenced by move().
correctDirection()
std::vector< std::pair< int, int > > Pawn::correctDirection (std::vector< std::pair< int, int > > steps) const
{
  std::vector<std::pair<int, int>> reverseSteps { std::vector<std::pair<int, int>>(steps) };
  if (this->color == PawnColor::BLACK) {
    std::ranges::transform(steps.begin(), steps.end(), reverseSteps.begin(), [](const std::pair<int, int> &pair){
      return std::make_pair(-pair.first, -pair.second);
    });
  }
  return reverseSteps;
}
References BLACK, and color.
Referenced by getAdvanceableSquares(), Bishop::getBlockedPawn(), Queen::getBlockedPawn(), and Rook::getBlockedPawn().
draw()
void Pawn::draw () override virtual
Implements Drawable.
                {
  this->drawingArea.draw();
}
References Rectangle::draw(), and drawingArea.
getAdvanceableSquares() [1/2]
virtual std::vector< std::pair< int, int > > Pawn::getAdvanceableSquares () pure virtual
Implemented in Bishop, King, Knight, Queen, Rook, and Soldier.
Referenced by Bishop::getAdvanceableSquares(), King::getAdvanceableSquares(), Knight::getAdvanceableSquares(), Queen::getAdvanceableSquares(), Rook::getAdvanceableSquares(), Soldier::getAdvanceableSquares(), Bishop::getHoldingSquares(), King::getHoldingSquares(), Knight::getHoldingSquares(), Queen::getHoldingSquares(), Rook::getHoldingSquares(), and Soldier::getHoldingSquares().
getAdvanceableSquares() [2/2]
std::vector< std::pair< int, int > > Pawn::getAdvanceableSquares (const std::vector< pair > & steps, unsigned short int maxSteps, bool holding) const virtual
{
  std::vector<std::pair<int, int>> advanceableSquares{std::vector<std::pair<int, int>>()};
  auto game{static_cast<App *>(graphics::getUserData())->getGame().lock()};
  auto checkboard{game->getCheckboard()};
  if (checkboard == nullptr) {
    return advanceableSquares;
  }
  const unsigned short int currentRow{this->getSquare().lock()->getRow()};
  const unsigned short int currentColumn{this->getSquare().lock()->getColumn()};
  unsigned short int nextRow{currentRow};
  unsigned short int nextColumn{currentColumn};
  for (const auto &[rowStep, columnStep]: this->correctDirection(steps)) {
    bool shouldTerminate{false};
    unsigned short int numberOfSteps{0};
    while (!shouldTerminate) {
      nextRow += rowStep;
      nextColumn += columnStep;
      if ((nextRow >= Checkboard::sideSize || nextColumn >= Checkboard::sideSize) || numberOfSteps == maxSteps) {
        shouldTerminate = { true };
        continue;
      }
      ++numberOfSteps;
      std::pair<int, int> squareCoordinates { std::make_pair<int, int>(nextRow, nextColumn) };
      auto [hasPawn, pawnColor] { checkboard->getSquareInfo(squareCoordinates) };
      if (hasPawn) {
        shouldTerminate = { true };
      }
      if (holding && hasPawn && pawnColor.value() != this->getColor() && checkboard->isKing(pawnColor.value(), squareCoordinates)) {
        shouldTerminate = { false };
      }
      if (const bool advanceOnPawn { hasPawn && (holding || pawnColor.value() != this->getColor()) }; advanceOnPawn || !hasPawn) {
        advanceableSquares.push_back(squareCoordinates);
      }
    }
    nextRow = { currentRow };
    nextColumn = { currentColumn };
  }
  return advanceableSquares;
}
References correctDirection(), getColor(), getSquare(), and Checkboard::sideSize.
getBlockedPawn()
std::weak_ptr< Pawn > Pawn::getBlockedPawn () virtual
Reimplemented in Bishop, Queen, and Rook.
{
  return std::weak_ptr<Pawn>();
}
getBlockingPawn()
std::weak_ptr< Pawn > Pawn::getBlockingPawn ()
{
  return this->blockingPawn;
}
References blockingPawn.
getColor()
PawnColor Pawn::getColor () const
{
  return this->color;
}
References color.
Referenced by King::castle(), Soldier::getAdvanceableSquares(), getAdvanceableSquares(), Bishop::getBlockedPawn(), Queen::getBlockedPawn(), Rook::getBlockedPawn(), King::getKingSquares(), King::isChecked(), and setSquare().
getDrawingArea()
std::weak_ptr< Rectangle > Pawn::getDrawingArea () const
{
  return std::make_shared<Rectangle>(this->drawingArea);
}
References drawingArea.
getHoldingSquares()
virtual std::vector< std::pair< int, int > > Pawn::getHoldingSquares () pure virtual
Implemented in Bishop, King, Knight, Queen, Rook, and Soldier.
getSquare()
std::weak_ptr< Square > Pawn::getSquare () const
{
  return this->square_;
}
References square_.
Referenced by King::castle(), Soldier::getAdvanceableSquares(), getAdvanceableSquares(), Bishop::getBlockedPawn(), Queen::getBlockedPawn(), Rook::getBlockedPawn(), and King::isChecked().
getTexture()
const std::string & Pawn::getTexture () const
{
  return this->texture_;
}
References texture_.
isBlocked()
bool Pawn::isBlocked () const
{
  return this->blocked;
}
References blocked.
move()
void Pawn::move (float ms) override virtual
Implements Movable.
{
  if (this->shouldMove && this->square_.lock() != nullptr) {
    auto checkboard{static_cast<App *>(graphics::getUserData())->getGame().lock()->getCheckboard()};
    this->drawingArea.setLeftBottom(this->drawingArea.getLeftBottom() + Point(this->moveSteps.second, this->moveSteps.first));
    checkboard->setMovingSquare(this->drawingArea.getLeftBottom(), this->drawingArea.getBrush(), this->drawingArea.getBrushType());
    auto squareDrawingArea{this->square_.lock()->getDrawingArea().lock()};
    auto destinationDrawingArea{this->destination_.lock()->getDrawingArea().lock()};
    if (squareDrawingArea->getLeftBottom() == destinationDrawingArea->getLeftBottom()) {
      if (this->destination_.lock()->hasPawn()) {
        this->capture(this->destination_.lock()->getPawn());
      }
      this->movingSquare.lock()->unregisterPawn();
      this->movingSquare.reset();
      this->square_.lock()->unregisterPawn();
      this->square_ = {this->destination_};
      this->square_.lock()->registerPawn(this->shared_from_this());
      this->destination_.reset();
      this->moveSteps = {};
      this->shouldMove = {false};
      checkboard->resetMovingSquare();
      checkboard->checkForCheckmate(this->shared_from_this());
      checkboard->setPawnMoving(false);
    }
  }
}
References capture(), destination_, drawingArea, Rectangle::getBrush(), Rectangle::getBrushType(), Rectangle::getLeftBottom(), moveSteps, movingSquare, Rectangle::setLeftBottom(), shouldMove, and square_.
Referenced by update().
moveTo()
void Pawn::moveTo (const std::shared_ptr< Square > & squarePtr, const std::shared_ptr< Pawn > & self)
{
  this->shouldMove = {true};
  this->destination_ = {squarePtr};
  this->movingSquare = {this->square_};
  constexpr long ms{2};
  const float rowDirection{-static_cast<float>(this->destination_.lock()->getRow() - this->square_.lock()->getRow())};
  const float columnDirection{static_cast<float>(this->destination_.lock()->getColumn() - this->square_.lock()->getColumn())};
  this->moveSteps = {std::make_pair(rowDirection / ms, columnDirection / ms)};
  if (this->self_ == nullptr) {
    this->self_ = {self};
  }
  auto checkboard{static_cast<App *>(graphics::getUserData())->getGame().lock()->getCheckboard()};
  checkboard->setMovingSquare(this->drawingArea.getLeftBottom(), this->drawingArea.getBrush(), this->drawingArea.getBrushType());
  this->square_ = {checkboard->getMovingSquare().lock()};
  this->square_.lock()->setRow(this->destination_.lock()->getRow());
  this->square_.lock()->setColumn(this->destination_.lock()->getColumn());
  this->square_.lock()->registerPawn(this->shared_from_this());
  this->moveSound.play();
}
References destination_, drawingArea, Rectangle::getBrush(), Rectangle::getBrushType(), Rectangle::getLeftBottom(), moveSound, moveSteps, movingSquare, Sound::play(), self_, shouldMove, and square_.
setSquare()
void Pawn::setSquare (const std::shared_ptr< Square > & square)
{
  this->square_ = {square};
  this->drawingArea.setHeight(square->getDrawingArea().lock()->getHeight());
  this->drawingArea.setWidth(square->getDrawingArea().lock()->getWidth());
  this->drawingArea.setLeftBottom(square->getDrawingArea().lock()->getLeftBottom());
  graphics::Brush pawn{Rectangle::colors.at(Brush::TEXTURE)};
  pawn.texture = {paths::getImagesPath() + this->texture_ + "-" + this->getColor() + this->png};
  this->drawingArea.setBrush(Brush::TEXTURE, pawn);
}
References Rectangle::colors, drawingArea, getColor(), paths::getImagesPath(), png, Rectangle::setBrush(), Rectangle::setHeight(), Rectangle::setLeftBottom(), Rectangle::setWidth(), square_, TEXTURE, and texture_.
setTexture()
void Pawn::setTexture (std::string texture)
{
  this->texture_ = { std::move(texture) };
}
References texture_.
Referenced by Bishop::Bishop(), King::King(), Knight::Knight(), Queen::Queen(), Rook::Rook(), and Soldier::Soldier().
unblock()
void Pawn::unblock ()
                   {
  this->blocked = {false};
  this->blockingPawn.reset();
}
References blocked, and blockingPawn.
update()
void Pawn::update (float ms) override virtual
Implements Updateable.
{
  if (this->drawingArea.clicked()) {
    this->clickSound.play();
  }
  this->move(ms);
}
References Rectangle::clicked(), clickSound, drawingArea, move(), and Sound::play().
Member Data Documentation
blocked
bool Pawn::blocked {false} private
Referenced by block(), isBlocked(), and unblock().
blockingPawn
std::weak_ptr<Pawn> Pawn::blockingPawn {std::weak_ptr<Pawn>()} private
Referenced by blockedBy(), getBlockingPawn(), and unblock().
captureSound
CaptureSound Pawn::captureSound {CaptureSound()} private
Referenced by capture().
clickSound
ClickSound Pawn::clickSound {ClickSound()} private
Referenced by update().
color
PawnColor Pawn::color private
Referenced by correctDirection(), and getColor().
destination_
std::weak_ptr<Square> Pawn::destination_ {std::weak_ptr<Square>()} private
Referenced by move(), and moveTo().
drawingArea
Rectangle Pawn::drawingArea {Rectangle()} private
Referenced by draw(), getDrawingArea(), move(), moveTo(), setSquare(), and update().
moveSound
MoveSound Pawn::moveSound {MoveSound()} private
Referenced by moveTo().
moveSteps
std::pair<float, float> Pawn::moveSteps {} private
Referenced by move(), and moveTo().
movingSquare
std::weak_ptr<Square> Pawn::movingSquare {std::weak_ptr<Square>()} private
Referenced by move(), and moveTo().
png
const std::string Pawn::png {".png"} private
Referenced by setSquare().
self_
std::shared_ptr<Pawn> Pawn::self_ {nullptr} private
Referenced by moveTo().
shouldMove
bool Pawn::shouldMove {false} private
Referenced by move(), and moveTo().
square_
std::weak_ptr<Square> Pawn::square_ {std::weak_ptr<Square>()} private
Referenced by getSquare(), move(), moveTo(), and setSquare().
texture_
std::string Pawn::texture_ {} private
Referenced by getTexture(), setSquare(), and setTexture().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/src/game/game/Pawn.h
/Users/runner/work/chess/chess/src/game/src/Pawn.cpp