Chess: /Users/runner/work/chess/chess/include/sgg/sgg/audio.h File Reference
audio.h File Reference
#include <SDL2/SDL.h>
Classes
struct sound
Typedefs
typedef struct sound Audio
Functions
Audio * createAudio (const char *filename, uint8_t loop, int volume)
void freeAudio (Audio *audio)
void playSound (const char *filename, int volume)
void playMusic (const char *filename, int volume)
void playSoundFromMemory (Audio *audio, int volume)
void playMusicFromMemory (Audio *audio, int volume)
void endAudio (void)
void initAudio (void)
void pauseAudio (void)
void unpauseAudio (void)
Typedef Documentation
Audio
typedef struct sound Audio
Function Documentation
createAudio()
Audio * createAudio (const char * filename, uint8_t loop, int volume)
{
    Audio * news = (Audio*)calloc(1, sizeof(Audio));
    if(news == NULL)
    {
        fprintf(stderr, "[%s: %d]Error: Memory allocation error\n", __FILE__, __LINE__);
        return NULL;
    }
    if(filename == NULL)
    {
        fprintf(stderr, "[%s: %d]Warning: filename NULL: %s\n", __FILE__, __LINE__, filename);
        return NULL;
    }
    news->next = NULL;
    news->loop = loop;
    news->fade = 0;
    news->free = 1;
    news->volume = volume;
    if(SDL_LoadWAV(filename, &(news->audio), &(news->bufferTrue), &(news->lengthTrue)) == NULL)
    {
        fprintf(stderr, "[%s: %d]Warning: failed to open wave file: %s error: %s\n", __FILE__, __LINE__, filename, SDL_GetError());
        free(news);
        return NULL;
    }
    news->buffer = news->bufferTrue;
    news->length = news->lengthTrue;
    (news->audio).callback = NULL;
    (news->audio).userdata = NULL;
    return news;
}
References sound::audio, sound::buffer, sound::bufferTrue, sound::fade, sound::free, sound::length, sound::lengthTrue, sound::loop, sound::next, and sound::volume.
Referenced by playAudio().
endAudio()
void endAudio (void)
{
    if(gDevice->audioEnabled)
    {
        pauseAudio();
        freeAudio((Audio *) (gDevice->want).userdata);
        /* Close down audio */
        SDL_CloseAudioDevice(gDevice->device);
    }
    free(gDevice);
}
References privateAudioDevice::audioEnabled, privateAudioDevice::device, freeAudio(), gDevice, pauseAudio(), and privateAudioDevice::want.
freeAudio()
void freeAudio (Audio * audio)
{
    Audio * temp;
    while(audio != NULL)
    {
        if(audio->free == 1)
        {
            SDL_FreeWAV(audio->bufferTrue);
        }
        temp = audio;
        audio = audio->next;
        free(temp);
    }
}
References sound::bufferTrue, sound::free, and sound::next.
Referenced by audioCallback(), and endAudio().
initAudio()
void initAudio (void)
{
    Audio * global;
    gDevice = (PrivateAudioDevice*)calloc(1, sizeof(PrivateAudioDevice));
    gSoundCount = 0;
    if(gDevice == NULL)
    {
        fprintf(stderr, "[%s: %d]Fatal Error: Memory c-allocation error\n", __FILE__, __LINE__);
        return;
    }
    gDevice->audioEnabled = 0;
    if(!(SDL_WasInit(SDL_INIT_AUDIO) & SDL_INIT_AUDIO))
    {
        fprintf(stderr, "[%s: %d]Error: SDL_INIT_AUDIO not initialized\n", __FILE__, __LINE__);
        return;
    }
    SDL_memset(&(gDevice->want), 0, sizeof(gDevice->want));
    (gDevice->want).freq = AUDIO_FREQUENCY;
    (gDevice->want).format = AUDIO_FORMAT;
    (gDevice->want).channels = AUDIO_CHANNELS;
    (gDevice->want).samples = AUDIO_SAMPLES;
    (gDevice->want).callback = audioCallback;
    (gDevice->want).userdata = calloc(1, sizeof(Audio));
    global = (Audio*)(gDevice->want).userdata;
    if(global == NULL)
    {
        fprintf(stderr, "[%s: %d]Error: Memory allocation error\n", __FILE__, __LINE__);
        return;
    }
    global->buffer = NULL;
    global->next = NULL;
    /* want.userdata = new; */
    if((gDevice->device = SDL_OpenAudioDevice(NULL, 0, &(gDevice->want), NULL, SDL_AUDIO_ALLOW_CHANGES)) == 0)
    {
        fprintf(stderr, "[%s: %d]Warning: failed to open audio device: %s\n", __FILE__, __LINE__, SDL_GetError());
    }
    else
    {
        /* Set audio device enabled global flag */
        gDevice->audioEnabled = 1;
        /* Unpause active audio stream */
        unpauseAudio();
    }
}
References AUDIO_CHANNELS, AUDIO_FORMAT, AUDIO_FREQUENCY, AUDIO_SAMPLES, audioCallback(), privateAudioDevice::audioEnabled, sound::buffer, privateAudioDevice::device, gDevice, gSoundCount, sound::next, SDL_AUDIO_ALLOW_CHANGES, unpauseAudio(), and privateAudioDevice::want.
pauseAudio()
void pauseAudio (void)
{
    if(gDevice->audioEnabled)
    {
        SDL_PauseAudioDevice(gDevice->device, 1);
    }
}
References privateAudioDevice::audioEnabled, privateAudioDevice::device, and gDevice.
Referenced by endAudio().
playMusic()
void playMusic (const char * filename, int volume)
{
    playAudio(filename, NULL, 1, volume);
}
References playAudio().
playMusicFromMemory()
void playMusicFromMemory (Audio * audio, int volume)
{
    playAudio(NULL, audio, 1, volume);
}
References playAudio().
playSound()
void playSound (const char * filename, int volume)
{
    playAudio(filename, NULL, 0, volume);
}
References playAudio().
playSoundFromMemory()
void playSoundFromMemory (Audio * audio, int volume)
{
    playAudio(NULL, audio, 0, volume);
}
References playAudio().
unpauseAudio()
void unpauseAudio (void)
{
    if(gDevice->audioEnabled)
    {
        SDL_PauseAudioDevice(gDevice->device, 0);
    }
}
References privateAudioDevice::audioEnabled, privateAudioDevice::device, and gDevice.
Referenced by initAudio().