Chess: Rook Class Reference
Rook Class Reference
#include <Rook.h>
Public Member Functions
Rook (PawnColor color)
std::vector< std::pair< int, int > > getAdvanceableSquares () override
std::vector< std::pair< int, int > > getHoldingSquares () override
std::weak_ptr< Pawn > getBlockedPawn () override
void setMoved ()
bool getMoved () const
Public Member Functions inherited from Pawn
Pawn (PawnColor color)
void setSquare (const std::shared_ptr< Square > &square)
void capture (const std::shared_ptr< Pawn > &pawn)
std::weak_ptr< Square > getSquare () const
PawnColor getColor () const
void setTexture (std::string texture)
const std::string & getTexture () const
std::weak_ptr< Rectangle > getDrawingArea () const
void draw () override
void update (float ms) override
void move (float ms) override
void moveTo (const std::shared_ptr< Square > &squarePtr, const std::shared_ptr< Pawn > &self)
virtual std::vector< std::pair< int, int > > getAdvanceableSquares ()=0
virtual std::vector< std::pair< int, int > > getHoldingSquares ()=0
virtual std::vector< std::pair< int, int > > getAdvanceableSquares (const std::vector< pair > &steps, unsigned short int maxSteps, bool holding) const
std::vector< std::pair< int, int > > correctDirection (std::vector< std::pair< int, int > > steps) const
virtual std::weak_ptr< Pawn > getBlockedPawn ()
std::weak_ptr< Pawn > getBlockingPawn ()
bool isBlocked () const
void block ()
void unblock ()
void blockedBy (const std::shared_ptr< Pawn > &blocking)
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Public Member Functions inherited from Movable
Movable ()=default
virtual void move (float ms)=0
virtual ~Movable ()=default
Private Attributes
std::vector< std::pair< int, int > > steps {std::vector<std::pair<int, int>>()}
bool hasMoved {false}
Static Private Attributes
static constexpr unsigned short int maxSteps {8}
Constructor & Destructor Documentation
Rook()
Rook::Rook (PawnColor color) explicit
                          : Pawn(color) {
  Pawn::setTexture("rook");
  this->steps.push_back(std::make_pair<int, int>(1, 0));
  this->steps.push_back(std::make_pair<int, int>(-1, 0));
  this->steps.push_back(std::make_pair<int, int>(0, 1));
  this->steps.push_back(std::make_pair<int, int>(0, -1));
}
References Pawn::setTexture(), and steps.
Member Function Documentation
getAdvanceableSquares()
std::vector< std::pair< int, int > > Rook::getAdvanceableSquares () override virtual
Implements Pawn.
{
  return Pawn::getAdvanceableSquares(this->steps, Rook::maxSteps, false);
}
References Pawn::getAdvanceableSquares(), maxSteps, and steps.
getBlockedPawn()
std::weak_ptr< Pawn > Rook::getBlockedPawn () override virtual
Reimplemented from Pawn.
{
  auto game{static_cast<App *>(graphics::getUserData())->getGame().lock()};
  auto checkboard{game->getCheckboard()};
  const unsigned short int currentRow{this->getSquare().lock()->getRow()};
  const unsigned short int currentColumn{this->getSquare().lock()->getColumn()};
  unsigned short int nextRow{currentRow};
  unsigned short int nextColumn{currentColumn};
  for (const auto &[rowStep, columnStep]: Pawn::correctDirection(this->steps)) {
    bool shouldTerminate{false};
    bool foundPawn{false};
    std::shared_ptr<Pawn> pawn{nullptr};
    unsigned short int numberOfSteps{0};
    while (!shouldTerminate) {
      nextRow += rowStep;
      nextColumn += columnStep;
      if ((nextRow >= Checkboard::sideSize || nextColumn >= Checkboard::sideSize) || numberOfSteps == Rook::maxSteps) {
        shouldTerminate = { true };
        continue;
      }
      ++numberOfSteps;
      std::pair<int, int> squareCoordinates { std::make_pair<int, int>(nextRow, nextColumn) };
      auto [hasPawn, pawnColor] { checkboard->getSquareInfo(squareCoordinates) };
      if (hasPawn && pawnColor != Pawn::getColor() && foundPawn && checkboard->isKing(pawn->getColor(), squareCoordinates)) {
        return pawn;
      }
      if (hasPawn && pawnColor != Pawn::getColor() && foundPawn) {
        shouldTerminate = { true };
      }
      if (hasPawn && pawnColor != Pawn::getColor()) {
        pawn = {checkboard->getSquare(squareCoordinates).lock()->getPawn()};
        foundPawn = {true};
      }
    }
    nextRow = {currentRow};
    nextColumn = {currentColumn};
  }
  return std::weak_ptr<Pawn>();
}
References Pawn::correctDirection(), Pawn::getColor(), Pawn::getSquare(), maxSteps, Checkboard::sideSize, and steps.
getHoldingSquares()
std::vector< std::pair< int, int > > Rook::getHoldingSquares () override virtual
Implements Pawn.
{
  return Pawn::getAdvanceableSquares(this->steps, Rook::maxSteps, true);
}
References Pawn::getAdvanceableSquares(), maxSteps, and steps.
getMoved()
bool Rook::getMoved () const
{
  return this->hasMoved;
}
References hasMoved.
setMoved()
void Rook::setMoved ()
                    {
  this->hasMoved = {true};
}
References hasMoved.
Member Data Documentation
hasMoved
bool Rook::hasMoved {false} private
Referenced by getMoved(), and setMoved().
maxSteps
constexpr unsigned short int Rook::maxSteps {8} static constexpr private
Referenced by getAdvanceableSquares(), getBlockedPawn(), and getHoldingSquares().
steps
std::vector<std::pair<int, int> > Rook::steps {std::vector<std::pair<int, int>>()} private
Referenced by getAdvanceableSquares(), getBlockedPawn(), getHoldingSquares(), and Rook().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/src/game/game/Rook.h
/Users/runner/work/chess/chess/src/game/src/Rook.cpp