Chess: AudioManager Class Reference
AudioManager Class Reference
#include <AudioManager.h>
Public Member Functions
void playSound (std::string soundfile, float volume, bool looping=false)
void playMusic (std::string soundfile, float volume, bool looping=true, int fade_time=0)
void stopMusic (int fade_time=0)
AudioManager ()
~AudioManager ()
Private Attributes
std::unordered_map< std::string, Mix_Chunk * > sounds
std::unordered_map< std::string, Mix_Music * > scores
bool initialized = true
Constructor & Destructor Documentation
AudioManager()
AudioManager::AudioManager ()
{
  if (Mix_OpenAudio(44100, MIX_DEFAULT_FORMAT, 2, 4096) == -1)
    return;
  initialized = true;
}
References initialized.
~AudioManager()
AudioManager::~AudioManager ()
{
  for (auto sound : sounds)
    Mix_FreeChunk(sound.second);
  for (auto score : scores)
    Mix_FreeMusic(score.second);
  Mix_CloseAudio();
}
References scores, and sounds.
Member Function Documentation
playMusic()
void AudioManager::playMusic (std::string soundfile, float volume, bool looping = true, int fade_time = 0)
{
  auto siter = scores.find(soundfile);
  if (siter == scores.end())
  {
    Mix_Music * ms = Mix_LoadMUS(soundfile.c_str());
    if (ms)
    {
      scores.insert(std::pair<std::string, Mix_Music*>(soundfile, ms));
      Mix_VolumeMusic((unsigned char)(MIX_MAX_VOLUME*volume));
      Mix_FadeInMusic(ms, looping ? -1 : 1, fade_time);
    }
  }
  else
  {
    Mix_VolumeMusic((unsigned char)(MIX_MAX_VOLUME*volume));
    Mix_FadeInMusic(siter->second, looping ? -1 : 1, fade_time);
  }
}
References scores.
Referenced by graphics::GLBackend::playMusic().
playSound()
void AudioManager::playSound (std::string soundfile, float volume, bool looping = false)
{
  auto siter = sounds.find(soundfile);
  if (siter == sounds.end())
  {
    Mix_Chunk * as = Mix_LoadWAV(soundfile.c_str());
    if (as)
    {
      sounds.insert(std::pair<std::string, Mix_Chunk*>(soundfile, as));
      Mix_VolumeChunk(as, (unsigned char)(MIX_MAX_VOLUME*volume));
      Mix_PlayChannel(-1, as, looping ? -1 : 0);
    }
  }
  else
  {
    Mix_VolumeChunk(siter->second, (unsigned char)(MIX_MAX_VOLUME*volume));
    Mix_PlayChannel(-1, siter->second, looping ? -1 : 0);
  }
}
References sounds.
Referenced by graphics::GLBackend::playSound().
stopMusic()
void AudioManager::stopMusic (int fade_time = 0)
{
  Mix_FadeOutMusic(fade_time);
}
Referenced by graphics::GLBackend::stopMusic().
Member Data Documentation
initialized
bool AudioManager::initialized = true private
Referenced by AudioManager().
scores
std::unordered_map<std::string, Mix_Music*> AudioManager::scores private
Referenced by playMusic(), and ~AudioManager().
sounds
std::unordered_map<std::string, Mix_Chunk*> AudioManager::sounds private
Referenced by playSound(), and ~AudioManager().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/include/sgg/sgg/AudioManager.h
/Users/runner/work/chess/chess/include/sgg/sgg/AudioManager.cpp