Chess: MainMenu Class Reference
MainMenu Class Reference
#include <MainMenu.h>
Public Member Functions
MainMenu ()
void draw () override
void update (float ms) override
void pressButton (const ButtonType &type) const override
Public Member Functions inherited from Menu
Menu ()
void draw () override=0
void update (float ms) override=0
void addOption (const MenuOption &option, ButtonType buttonType)
const MenuOption & getMenuOption (ButtonType buttonType)
const std::unordered_map< ButtonType, MenuOption > & getMenuOptions () const
virtual void pressButton (const ButtonType &type) const =0
Public Member Functions inherited from Drawable
virtual void draw ()=0
virtual ~Drawable ()=default
Public Member Functions inherited from Updateable
virtual void update (float ms)=0
virtual ~Updateable ()=default
Static Public Member Functions
static MenuOption createMenuOption (std::string message, float verticalPoint)
Constructor & Destructor Documentation
MainMenu()
MainMenu::MainMenu ()
                   {
  Menu::addOption(MainMenu::createMenuOption("Start a game", 400.0f), ButtonType::PLAY);
}
References Menu::addOption(), createMenuOption(), and PLAY.
Member Function Documentation
createMenuOption()
MenuOption MainMenu::createMenuOption (std::string message, float verticalPoint) static
{
  const std::size_t size { 80 };
  const float horizontalPoint { 1025 - static_cast<float>(message.length()) * size / 2 };
  const auto coordinates { std::make_pair(horizontalPoint, verticalPoint) };
  HUD menuHud { HUD(std::move(message), coordinates, size) };
  menuHud.setTextBrush(Brush::LIGHT_BROWN);
  return MenuOption(menuHud);
}
References LIGHT_BROWN, and HUD::setTextBrush().
Referenced by MainMenu().
draw()
void MainMenu::draw () override virtual
Implements Menu.
                    {
  for (const auto& [type, option] : Menu::getMenuOptions()) {
    option.getMessage().draw();
    option.getButton().draw();
  }
}
References Menu::getMenuOptions().
pressButton()
void MainMenu::pressButton (const ButtonType & type) const override virtual
Implements Menu.
{
  if (type == ButtonType::PLAY) {
    App *app {static_cast<App *>(graphics::getUserData())};
    app->changeScreen(std::make_shared<PlayingScreen>());
  }
}
References App::changeScreen(), and PLAY.
Referenced by update().
update()
void MainMenu::update (float ms) override virtual
Implements Menu.
{
  if (Menu::getMenuOption(ButtonType::PLAY).getButton().clicked()) {
    this->pressButton(ButtonType::PLAY);
  }
  for (const auto& [type, option] : Menu::getMenuOptions()) {
    option.getMessage().update(ms);
    option.getButton().update(ms);
  }
}
References Menu::getMenuOption(), Menu::getMenuOptions(), PLAY, and pressButton().
The documentation for this class was generated from the following files:
/Users/runner/work/chess/chess/include/graphics/MainMenu.h
/Users/runner/work/chess/chess/src/graphics/MainMenu.cpp